/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../app/components/signup/signup.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/debug_context';
import * as import3 from '../../../../app/services/profile.service';
import * as import4 from '@angular/core/src/render/api';
import * as import5 from '@angular/core/src/linker/view_utils';
import * as import6 from '@angular/core/src/metadata/view';
import * as import7 from '@angular/core/src/linker/view_type';
import * as import8 from '@angular/core/src/change_detection/change_detection';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from '@angular/http/src/http';
import * as import11 from '@angular/router/src/router';
import * as import12 from './signup.component.css';
import * as import13 from '@angular/material/card/card';
import * as import14 from '@angular/material/core/compatibility/style-compatibility';
import * as import15 from '@angular/forms/src/directives/ng_form';
import * as import16 from '@angular/forms/src/directives/control_container';
import * as import17 from '@angular/forms/src/directives/ng_control_status';
import * as import18 from '@angular/material/input/input';
import * as import19 from '@angular/forms/src/directives/control_value_accessor';
import * as import20 from '@angular/forms/src/directives/ng_model';
import * as import21 from '@angular/forms/src/directives/ng_control';
import * as import22 from '@angular/material/button/button';
import * as import23 from '../../../node_modules/@angular/material/card/card.ngfactory';
import * as import24 from '../../../node_modules/@angular/material/core/compatibility/style-compatibility.ngfactory';
import * as import25 from '../../../node_modules/@angular/forms/src/directives/ng_form.ngfactory';
import * as import26 from '../../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import27 from '../../../node_modules/@angular/material/input/input.ngfactory';
import * as import28 from '../../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import29 from '@angular/core/src/linker/query_list';
import * as import30 from '../../../node_modules/@angular/material/button/button.ngfactory';
import * as import31 from '@angular/core/src/linker/element_ref';
export class Wrapper_SignupComponent {
  /*private*/ _eventHandler:Function;
  context:import0.SignupComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any) {
    this._changed = false;
    this.context = new import0.SignupComponent(p0,p1);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
  const nodeDebugInfos_SignupComponent_Host0:import2.StaticNodeDebugInfo[] = [new import2.StaticNodeDebugInfo([
    import3.ProfileService,
    import0.SignupComponent
  ]
,import0.SignupComponent,{})];
var renderType_SignupComponent_Host:import4.RenderComponentType = import5.createRenderComponentType('',0,import6.ViewEncapsulation.None,([] as any[]),{});
class View_SignupComponent_Host0 extends import1.DebugAppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.SignupComponent>;
  _ProfileService_0_3:import3.ProfileService;
  _SignupComponent_0_4:Wrapper_SignupComponent;
  constructor(viewUtils:import5.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_SignupComponent_Host0,renderType_SignupComponent_Host,import7.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_SignupComponent_Host0);
  }
  createInternal(rootSelector:string):import9.ComponentRef<any> {
    this._el_0 = import5.selectOrCreateRenderHostElement(this.renderer,'ng-component',import5.EMPTY_INLINE_ARRAY,rootSelector,this.debug(0,0,0));
    this.compView_0 = new View_SignupComponent0(this.viewUtils,this,0,this._el_0);
    this._ProfileService_0_3 = new import3.ProfileService(this.injectorGet(import10.Http,this.parentIndex));
    this._SignupComponent_0_4 = new Wrapper_SignupComponent(this._ProfileService_0_3,this.injectorGet(import11.Router,this.parentIndex));
    this.compView_0.create(this._SignupComponent_0_4.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import9.ComponentRef_<any>(0,this,this._el_0,this._SignupComponent_0_4.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.ProfileService) && (0 === requestNodeIndex))) { return this._ProfileService_0_3; }
    if (((token === import0.SignupComponent) && (0 === requestNodeIndex))) { return this._SignupComponent_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.debug(0,0,0);
    this._SignupComponent_0_4.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const SignupComponentNgFactory:import9.ComponentFactory<import0.SignupComponent> = new import9.ComponentFactory<import0.SignupComponent>('ng-component',View_SignupComponent_Host0,import0.SignupComponent);
const styles_SignupComponent:any[] = [import12.styles];
const nodeDebugInfos_SignupComponent0:import2.StaticNodeDebugInfo[] = [
  new import2.StaticNodeDebugInfo([
    import13.MdCard,
    import14.StyleCompatibility
  ]
  ,import13.MdCard,{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([
    import13.MdCardContent,
    import14.StyleCompatibility
  ]
  ,(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([
    import15.NgForm,
    import16.ControlContainer,
    import17.NgControlStatusGroup
  ]
  ,(null as any),{signupForm: import15.NgForm}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([
    import18.MdInput,
    import19.NG_VALUE_ACCESSOR,
    import20.NgModel,
    import21.NgControl,
    import17.NgControlStatus,
    import14.StyleCompatibility
  ]
  ,import18.MdInput,{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([
    import18.MdInput,
    import19.NG_VALUE_ACCESSOR,
    import20.NgModel,
    import21.NgControl,
    import17.NgControlStatus,
    import14.StyleCompatibility
  ]
  ,import18.MdInput,{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([
    import18.MdInput,
    import19.NG_VALUE_ACCESSOR,
    import20.NgModel,
    import21.NgControl,
    import17.NgControlStatus,
    import14.StyleCompatibility
  ]
  ,import18.MdInput,{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([import22.MdButton],import22.MdButton,{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{})
]
;
var renderType_SignupComponent:import4.RenderComponentType = import5.createRenderComponentType('/Users/jessebowden/ichuwt/frontend/src/app/components/signup/signup.component.html',0,import6.ViewEncapsulation.None,styles_SignupComponent,{});
export class View_SignupComponent0 extends import1.DebugAppView<import0.SignupComponent> {
  _el_0:any;
  compView_0:import1.AppView<import13.MdCard>;
  _MdCard_0_3:import23.Wrapper_MdCard;
  _StyleCompatibility_0_4:import24.Wrapper_StyleCompatibility;
  _text_1:any;
  _el_2:any;
  _MdCardContent_2_3:import23.Wrapper_MdCardContent;
  _StyleCompatibility_2_4:import24.Wrapper_StyleCompatibility;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _NgForm_14_3:import25.Wrapper_NgForm;
  _ControlContainer_14_4:any;
  _NgControlStatusGroup_14_5:import26.Wrapper_NgControlStatusGroup;
  _text_15:any;
  _el_16:any;
  compView_16:import1.AppView<import18.MdInput>;
  _MdInput_16_3:import27.Wrapper_MdInput;
  _NG_VALUE_ACCESSOR_16_4:any[];
  _NgModel_16_5:import28.Wrapper_NgModel;
  _NgControl_16_6:any;
  _NgControlStatus_16_7:import26.Wrapper_NgControlStatus;
  _StyleCompatibility_16_8:import24.Wrapper_StyleCompatibility;
  _query_MdPlaceholder_16_0:import29.QueryList<any>;
  _query_MdHint_16_1:import29.QueryList<any>;
  _text_17:any;
  _el_18:any;
  compView_18:import1.AppView<import18.MdInput>;
  _MdInput_18_3:import27.Wrapper_MdInput;
  _NG_VALUE_ACCESSOR_18_4:any[];
  _NgModel_18_5:import28.Wrapper_NgModel;
  _NgControl_18_6:any;
  _NgControlStatus_18_7:import26.Wrapper_NgControlStatus;
  _StyleCompatibility_18_8:import24.Wrapper_StyleCompatibility;
  _query_MdPlaceholder_18_0:import29.QueryList<any>;
  _query_MdHint_18_1:import29.QueryList<any>;
  _text_19:any;
  _el_20:any;
  compView_20:import1.AppView<import18.MdInput>;
  _MdInput_20_3:import27.Wrapper_MdInput;
  _NG_VALUE_ACCESSOR_20_4:any[];
  _NgModel_20_5:import28.Wrapper_NgModel;
  _NgControl_20_6:any;
  _NgControlStatus_20_7:import26.Wrapper_NgControlStatus;
  _StyleCompatibility_20_8:import24.Wrapper_StyleCompatibility;
  _query_MdPlaceholder_20_0:import29.QueryList<any>;
  _query_MdHint_20_1:import29.QueryList<any>;
  _text_21:any;
  _el_22:any;
  compView_22:import1.AppView<import22.MdButton>;
  _MdButton_22_3:import30.Wrapper_MdButton;
  _text_23:any;
  _text_24:any;
  _text_25:any;
  _text_26:any;
  _text_27:any;
  constructor(viewUtils:import5.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_SignupComponent0,renderType_SignupComponent,import7.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_SignupComponent0);
  }
  createInternal(rootSelector:string):import9.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import5.createRenderElement(this.renderer,parentRenderNode,'md-card',new import5.InlineArray4(4,'class','help_you','id','help_you'),this.debug(0,0,0));
    this.compView_0 = new import23.View_MdCard0(this.viewUtils,this,0,this._el_0);
    this._MdCard_0_3 = new import23.Wrapper_MdCard();
    this._StyleCompatibility_0_4 = new import24.Wrapper_StyleCompatibility(this.renderer,new import31.ElementRef(this._el_0));
    this._text_1 = this.renderer.createText((null as any),'\n  ',this.debug(1,0,40));
    this._el_2 = import5.createRenderElement(this.renderer,(null as any),'md-card-content',import5.EMPTY_INLINE_ARRAY,this.debug(2,1,2));
    this._MdCardContent_2_3 = new import23.Wrapper_MdCardContent();
    this._StyleCompatibility_2_4 = new import24.Wrapper_StyleCompatibility(this.renderer,new import31.ElementRef(this._el_2));
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',this.debug(3,1,19));
    this._el_4 = import5.createRenderElement(this.renderer,this._el_2,'img',new import5.InlineArray8(6,'class','content','md-card-image','','src','https://scontent.fbed1-2.fna.fbcdn.net/v/t1.0-9/15027882_10101666597237585_7556774340470305079_n.jpg?oh=635948e21d52a9aacc0ab9cc53a4e1ad&oe=58D120BD'),this.debug(4,2,4));
    this._text_5 = this.renderer.createText(this._el_2,'\n    ',this.debug(5,2,195));
    this._el_6 = import5.createRenderElement(this.renderer,this._el_2,'p',new import5.InlineArray2(2,'class','text login_footer'),this.debug(6,3,4));
    this._text_7 = this.renderer.createText(this._el_6,'\n      Want to help out? Get an invite from a friend or email us.',this.debug(7,3,33));
    this._el_8 = import5.createRenderElement(this.renderer,this._el_6,'br',import5.EMPTY_INLINE_ARRAY,this.debug(8,4,64));
    this._text_9 = this.renderer.createText(this._el_6,'\n      Organization in need of help?\n    ',this.debug(9,4,70));
    this._text_10 = this.renderer.createText(this._el_2,'\n    ',this.debug(10,6,8));
    this._el_11 = import5.createRenderElement(this.renderer,this._el_2,'p',import5.EMPTY_INLINE_ARRAY,this.debug(11,7,4));
    this._text_12 = this.renderer.createText(this._el_11,'\n      Sign-up',this.debug(12,7,7));
    this._text_13 = this.renderer.createText(this._el_2,'\n    ',this.debug(13,8,17));
    this._el_14 = import5.createRenderElement(this.renderer,this._el_2,'form',import5.EMPTY_INLINE_ARRAY,this.debug(14,9,4));
    this._NgForm_14_3 = new import25.Wrapper_NgForm((null as any),(null as any));
    this._ControlContainer_14_4 = this._NgForm_14_3.context;
    this._NgControlStatusGroup_14_5 = new import26.Wrapper_NgControlStatusGroup(this._ControlContainer_14_4);
    this._text_15 = this.renderer.createText(this._el_14,'\n      ',this.debug(15,9,53));
    this._el_16 = import5.createRenderElement(this.renderer,this._el_14,'md-input',new import5.InlineArray16(10,'align','start','class','login_input','id','name_input','name','name','placeholder','Name'),this.debug(16,10,6));
    this.compView_16 = new import27.View_MdInput0(this.viewUtils,this,16,this._el_16);
    this._MdInput_16_3 = new import27.Wrapper_MdInput(new import31.ElementRef(this._el_16));
    this._NG_VALUE_ACCESSOR_16_4 = [this._MdInput_16_3.context];
    this._NgModel_16_5 = new import28.Wrapper_NgModel(this._ControlContainer_14_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_16_4);
    this._NgControl_16_6 = this._NgModel_16_5.context;
    this._NgControlStatus_16_7 = new import26.Wrapper_NgControlStatus(this._NgControl_16_6);
    this._StyleCompatibility_16_8 = new import24.Wrapper_StyleCompatibility(this.renderer,new import31.ElementRef(this._el_16));
    this._query_MdPlaceholder_16_0 = new import29.QueryList<any>();
    this._query_MdHint_16_1 = new import29.QueryList<any>();
    this._query_MdPlaceholder_16_0.reset(([] as any[]));
    this._MdInput_16_3.context._placeholderChild = this._query_MdPlaceholder_16_0.first;
    this.compView_16.create(this._MdInput_16_3.context);
    this._text_17 = this.renderer.createText(this._el_14,'\n      ',this.debug(17,10,135));
    this._el_18 = import5.createRenderElement(this.renderer,this._el_14,'md-input',new import5.InlineArray16(10,'align','start','class','login_input','id','email_input','name','email','placeholder','E-Mail'),this.debug(18,11,6));
    this.compView_18 = new import27.View_MdInput0(this.viewUtils,this,18,this._el_18);
    this._MdInput_18_3 = new import27.Wrapper_MdInput(new import31.ElementRef(this._el_18));
    this._NG_VALUE_ACCESSOR_18_4 = [this._MdInput_18_3.context];
    this._NgModel_18_5 = new import28.Wrapper_NgModel(this._ControlContainer_14_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_18_4);
    this._NgControl_18_6 = this._NgModel_18_5.context;
    this._NgControlStatus_18_7 = new import26.Wrapper_NgControlStatus(this._NgControl_18_6);
    this._StyleCompatibility_18_8 = new import24.Wrapper_StyleCompatibility(this.renderer,new import31.ElementRef(this._el_18));
    this._query_MdPlaceholder_18_0 = new import29.QueryList<any>();
    this._query_MdHint_18_1 = new import29.QueryList<any>();
    this._query_MdPlaceholder_18_0.reset(([] as any[]));
    this._MdInput_18_3.context._placeholderChild = this._query_MdPlaceholder_18_0.first;
    this.compView_18.create(this._MdInput_18_3.context);
    this._text_19 = this.renderer.createText(this._el_14,'\n      ',this.debug(19,11,140));
    this._el_20 = import5.createRenderElement(this.renderer,this._el_14,'md-input',new import5.InlineArray16(10,'align','start','class','login_input','id','mission_input','name','mission','placeholder','Mission'),this.debug(20,12,6));
    this.compView_20 = new import27.View_MdInput0(this.viewUtils,this,20,this._el_20);
    this._MdInput_20_3 = new import27.Wrapper_MdInput(new import31.ElementRef(this._el_20));
    this._NG_VALUE_ACCESSOR_20_4 = [this._MdInput_20_3.context];
    this._NgModel_20_5 = new import28.Wrapper_NgModel(this._ControlContainer_14_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_20_4);
    this._NgControl_20_6 = this._NgModel_20_5.context;
    this._NgControlStatus_20_7 = new import26.Wrapper_NgControlStatus(this._NgControl_20_6);
    this._StyleCompatibility_20_8 = new import24.Wrapper_StyleCompatibility(this.renderer,new import31.ElementRef(this._el_20));
    this._query_MdPlaceholder_20_0 = new import29.QueryList<any>();
    this._query_MdHint_20_1 = new import29.QueryList<any>();
    this._query_MdPlaceholder_20_0.reset(([] as any[]));
    this._MdInput_20_3.context._placeholderChild = this._query_MdPlaceholder_20_0.first;
    this.compView_20.create(this._MdInput_20_3.context);
    this._text_21 = this.renderer.createText(this._el_14,'\n      ',this.debug(21,12,147));
    this._el_22 = import5.createRenderElement(this.renderer,this._el_14,'button',new import5.InlineArray8(8,'class','login_button','md-button','','style','color: white;','type','submit'),this.debug(22,13,6));
    this.compView_22 = new import30.View_MdButton0(this.viewUtils,this,22,this._el_22);
    this._MdButton_22_3 = new import30.Wrapper_MdButton(new import31.ElementRef(this._el_22),this.renderer);
    this._text_23 = this.renderer.createText((null as any),'Sign-up',this.debug(23,13,100));
    this.compView_22.create(this._MdButton_22_3.context);
    this._text_24 = this.renderer.createText(this._el_14,'\n    ',this.debug(24,13,116));
    this._text_25 = this.renderer.createText(this._el_2,'\n\n  ',this.debug(25,14,11));
    this._text_26 = this.renderer.createText((null as any),'\n',this.debug(26,16,20));
    this.compView_0.create(this._MdCard_0_3.context);
    this._text_27 = this.renderer.createText(parentRenderNode,'\n',this.debug(27,17,10));
    var disposable_0:Function = import5.subscribeToRenderElement(this,this._el_14,new import5.InlineArray8(6,'ngSubmit',(null as any),'submit',(null as any),'reset',(null as any)),this.eventHandler(this.handleEvent_14));
    this._NgForm_14_3.subscribe(this,this.eventHandler(this.handleEvent_14),true);
    var disposable_1:Function = import5.subscribeToRenderElement(this,this._el_16,new import5.InlineArray4(4,'ngModelChange',(null as any),'click',(null as any)),this.eventHandler(this.handleEvent_16));
    this._NgModel_16_5.subscribe(this,this.eventHandler(this.handleEvent_16),true);
    var disposable_2:Function = import5.subscribeToRenderElement(this,this._el_18,new import5.InlineArray4(4,'ngModelChange',(null as any),'click',(null as any)),this.eventHandler(this.handleEvent_18));
    this._NgModel_18_5.subscribe(this,this.eventHandler(this.handleEvent_18),true);
    var disposable_3:Function = import5.subscribeToRenderElement(this,this._el_20,new import5.InlineArray4(4,'ngModelChange',(null as any),'click',(null as any)),this.eventHandler(this.handleEvent_20));
    this._NgModel_20_5.subscribe(this,this.eventHandler(this.handleEvent_20),true);
    var disposable_4:Function = import5.subscribeToRenderElement(this,this._el_22,new import5.InlineArray8(8,'click',(null as any),'mousedown',(null as any),'focus',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_22));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._text_25,
      this._text_26,
      this._text_27
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import18.MdInput) && (16 === requestNodeIndex))) { return this._MdInput_16_3.context; }
    if (((token === import19.NG_VALUE_ACCESSOR) && (16 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_16_4; }
    if (((token === import20.NgModel) && (16 === requestNodeIndex))) { return this._NgModel_16_5.context; }
    if (((token === import21.NgControl) && (16 === requestNodeIndex))) { return this._NgControl_16_6; }
    if (((token === import17.NgControlStatus) && (16 === requestNodeIndex))) { return this._NgControlStatus_16_7.context; }
    if (((token === import14.StyleCompatibility) && (16 === requestNodeIndex))) { return this._StyleCompatibility_16_8.context; }
    if (((token === import18.MdInput) && (18 === requestNodeIndex))) { return this._MdInput_18_3.context; }
    if (((token === import19.NG_VALUE_ACCESSOR) && (18 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_18_4; }
    if (((token === import20.NgModel) && (18 === requestNodeIndex))) { return this._NgModel_18_5.context; }
    if (((token === import21.NgControl) && (18 === requestNodeIndex))) { return this._NgControl_18_6; }
    if (((token === import17.NgControlStatus) && (18 === requestNodeIndex))) { return this._NgControlStatus_18_7.context; }
    if (((token === import14.StyleCompatibility) && (18 === requestNodeIndex))) { return this._StyleCompatibility_18_8.context; }
    if (((token === import18.MdInput) && (20 === requestNodeIndex))) { return this._MdInput_20_3.context; }
    if (((token === import19.NG_VALUE_ACCESSOR) && (20 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_20_4; }
    if (((token === import20.NgModel) && (20 === requestNodeIndex))) { return this._NgModel_20_5.context; }
    if (((token === import21.NgControl) && (20 === requestNodeIndex))) { return this._NgControl_20_6; }
    if (((token === import17.NgControlStatus) && (20 === requestNodeIndex))) { return this._NgControlStatus_20_7.context; }
    if (((token === import14.StyleCompatibility) && (20 === requestNodeIndex))) { return this._StyleCompatibility_20_8.context; }
    if (((token === import22.MdButton) && ((22 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._MdButton_22_3.context; }
    if (((token === import15.NgForm) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 24)))) { return this._NgForm_14_3.context; }
    if (((token === import16.ControlContainer) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 24)))) { return this._ControlContainer_14_4; }
    if (((token === import17.NgControlStatusGroup) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 24)))) { return this._NgControlStatusGroup_14_5.context; }
    if (((token === import13.MdCardContent) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 25)))) { return this._MdCardContent_2_3.context; }
    if (((token === import14.StyleCompatibility) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 25)))) { return this._StyleCompatibility_2_4.context; }
    if (((token === import13.MdCard) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._MdCard_0_3.context; }
    if (((token === import14.StyleCompatibility) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._StyleCompatibility_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.debug(0,0,0);
    if (this._MdCard_0_3.ngDoCheck(this,this._el_0,throwOnChange)) { this.compView_0.markAsCheckOnce(); }
    this._StyleCompatibility_0_4.ngDoCheck(this,this._el_0,throwOnChange);
    this.debug(2,1,2);
    this._MdCardContent_2_3.ngDoCheck(this,this._el_2,throwOnChange);
    this._StyleCompatibility_2_4.ngDoCheck(this,this._el_2,throwOnChange);
    this.debug(14,9,4);
    this._NgForm_14_3.ngDoCheck(this,this._el_14,throwOnChange);
    this._NgControlStatusGroup_14_5.ngDoCheck(this,this._el_14,throwOnChange);
    this.debug(16,10,35);
    const currVal_16_0_0:any = 'start';
    this._MdInput_16_3.check_align(currVal_16_0_0,throwOnChange,false);
    this.debug(16,10,49);
    const currVal_16_0_1:any = 'name_input';
    this._MdInput_16_3.check_id(currVal_16_0_1,throwOnChange,false);
    this.debug(16,10,16);
    const currVal_16_0_2:any = 'Name';
    this._MdInput_16_3.check_placeholder(currVal_16_0_2,throwOnChange,false);
    this.debug(16,10,65);
    const currVal_16_0_3:any = 'name';
    this._MdInput_16_3.check_name(currVal_16_0_3,throwOnChange,false);
    this._MdInput_16_3.ngDoCheck(this,this._el_16,throwOnChange);
    this.debug(16,10,65);
    const currVal_16_1_0:any = 'name';
    this._NgModel_16_5.check_name(currVal_16_1_0,throwOnChange,false);
    this.debug(16,10,97);
    const currVal_16_1_1:any = this.context.profile.name;
    this._NgModel_16_5.check_model(currVal_16_1_1,throwOnChange,false);
    this._NgModel_16_5.ngDoCheck(this,this._el_16,throwOnChange);
    this.debug(16,10,6);
    this._NgControlStatus_16_7.ngDoCheck(this,this._el_16,throwOnChange);
    this._StyleCompatibility_16_8.ngDoCheck(this,this._el_16,throwOnChange);
    this.debug(18,11,37);
    const currVal_18_0_0:any = 'start';
    this._MdInput_18_3.check_align(currVal_18_0_0,throwOnChange,false);
    this.debug(18,11,51);
    const currVal_18_0_1:any = 'email_input';
    this._MdInput_18_3.check_id(currVal_18_0_1,throwOnChange,false);
    this.debug(18,11,16);
    const currVal_18_0_2:any = 'E-Mail';
    this._MdInput_18_3.check_placeholder(currVal_18_0_2,throwOnChange,false);
    this.debug(18,11,68);
    const currVal_18_0_3:any = 'email';
    this._MdInput_18_3.check_name(currVal_18_0_3,throwOnChange,false);
    this._MdInput_18_3.ngDoCheck(this,this._el_18,throwOnChange);
    this.debug(18,11,68);
    const currVal_18_1_0:any = 'email';
    this._NgModel_18_5.check_name(currVal_18_1_0,throwOnChange,false);
    this.debug(18,11,101);
    const currVal_18_1_1:any = this.context.profile.email;
    this._NgModel_18_5.check_model(currVal_18_1_1,throwOnChange,false);
    this._NgModel_18_5.ngDoCheck(this,this._el_18,throwOnChange);
    this.debug(18,11,6);
    this._NgControlStatus_18_7.ngDoCheck(this,this._el_18,throwOnChange);
    this._StyleCompatibility_18_8.ngDoCheck(this,this._el_18,throwOnChange);
    this.debug(20,12,38);
    const currVal_20_0_0:any = 'start';
    this._MdInput_20_3.check_align(currVal_20_0_0,throwOnChange,false);
    this.debug(20,12,52);
    const currVal_20_0_1:any = 'mission_input';
    this._MdInput_20_3.check_id(currVal_20_0_1,throwOnChange,false);
    this.debug(20,12,16);
    const currVal_20_0_2:any = 'Mission';
    this._MdInput_20_3.check_placeholder(currVal_20_0_2,throwOnChange,false);
    this.debug(20,12,71);
    const currVal_20_0_3:any = 'mission';
    this._MdInput_20_3.check_name(currVal_20_0_3,throwOnChange,false);
    this._MdInput_20_3.ngDoCheck(this,this._el_20,throwOnChange);
    this.debug(20,12,71);
    const currVal_20_1_0:any = 'mission';
    this._NgModel_20_5.check_name(currVal_20_1_0,throwOnChange,false);
    this.debug(20,12,106);
    const currVal_20_1_1:any = this.context.profile.mission;
    this._NgModel_20_5.check_model(currVal_20_1_1,throwOnChange,false);
    this._NgModel_20_5.ngDoCheck(this,this._el_20,throwOnChange);
    this.debug(20,12,6);
    this._NgControlStatus_20_7.ngDoCheck(this,this._el_20,throwOnChange);
    this._StyleCompatibility_20_8.ngDoCheck(this,this._el_20,throwOnChange);
    this.debug(22,13,6);
    if (this._MdButton_22_3.ngDoCheck(this,this._el_22,throwOnChange)) { this.compView_22.markAsCheckOnce(); }
    if (!throwOnChange) {
      if (this._query_MdHint_16_1.dirty) {
        this._query_MdHint_16_1.reset(([] as any[]));
        this._MdInput_16_3.context._hintChildren = this._query_MdHint_16_1;
        this._query_MdHint_16_1.notifyOnChanges();
      }
      if (this._query_MdHint_18_1.dirty) {
        this._query_MdHint_18_1.reset(([] as any[]));
        this._MdInput_18_3.context._hintChildren = this._query_MdHint_18_1;
        this._query_MdHint_18_1.notifyOnChanges();
      }
      if (this._query_MdHint_20_1.dirty) {
        this._query_MdHint_20_1.reset(([] as any[]));
        this._MdInput_20_3.context._hintChildren = this._query_MdHint_20_1;
        this._query_MdHint_20_1.notifyOnChanges();
      }
      this.debug(16,10,6);
      if ((this.numberOfChecks === 0)) { this._MdInput_16_3.context.ngAfterContentInit(); }
      this.debug(18,11,6);
      if ((this.numberOfChecks === 0)) { this._MdInput_18_3.context.ngAfterContentInit(); }
      this.debug(20,12,6);
      if ((this.numberOfChecks === 0)) { this._MdInput_20_3.context.ngAfterContentInit(); }
    }
    this._NgControlStatusGroup_14_5.checkHost(this,this,this._el_14,throwOnChange);
    this._MdInput_16_3.checkHost(this,this.compView_16,this._el_16,throwOnChange);
    this._NgControlStatus_16_7.checkHost(this,this.compView_16,this._el_16,throwOnChange);
    this._MdInput_18_3.checkHost(this,this.compView_18,this._el_18,throwOnChange);
    this._NgControlStatus_18_7.checkHost(this,this.compView_18,this._el_18,throwOnChange);
    this._MdInput_20_3.checkHost(this,this.compView_20,this._el_20,throwOnChange);
    this._NgControlStatus_20_7.checkHost(this,this.compView_20,this._el_20,throwOnChange);
    this._MdButton_22_3.checkHost(this,this.compView_22,this._el_22,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
    this.compView_16.detectChanges(throwOnChange);
    this.compView_18.detectChanges(throwOnChange);
    this.compView_20.detectChanges(throwOnChange);
    this.compView_22.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this.compView_16.destroy();
    this.compView_18.destroy();
    this.compView_20.destroy();
    this.compView_22.destroy();
    this._MdInput_16_3.ngOnDestroy();
    this._NgModel_16_5.ngOnDestroy();
    this.debug(16,10,6);
    this._MdInput_18_3.ngOnDestroy();
    this._NgModel_18_5.ngOnDestroy();
    this.debug(18,11,6);
    this._MdInput_20_3.ngOnDestroy();
    this._NgModel_20_5.ngOnDestroy();
    this.debug(20,12,6);
    this.debug(22,13,6);
    this._NgForm_14_3.ngOnDestroy();
    this.debug(14,9,4);
    this.debug(2,1,2);
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 0) && (ngContentIndex == 0))) {
      cb(this._text_1,ctx);
      cb(this._el_2,ctx);
      cb(this._text_26,ctx);
    }
    if (((nodeIndex == 16) && (ngContentIndex == 0))) {  }
    if (((nodeIndex == 16) && (ngContentIndex == 1))) {  }
    if (((nodeIndex == 16) && (ngContentIndex == 2))) {  }
    if (((nodeIndex == 16) && (ngContentIndex == 3))) {  }
    if (((nodeIndex == 18) && (ngContentIndex == 0))) {  }
    if (((nodeIndex == 18) && (ngContentIndex == 1))) {  }
    if (((nodeIndex == 18) && (ngContentIndex == 2))) {  }
    if (((nodeIndex == 18) && (ngContentIndex == 3))) {  }
    if (((nodeIndex == 20) && (ngContentIndex == 0))) {  }
    if (((nodeIndex == 20) && (ngContentIndex == 1))) {  }
    if (((nodeIndex == 20) && (ngContentIndex == 2))) {  }
    if (((nodeIndex == 20) && (ngContentIndex == 3))) {  }
    if (((nodeIndex == 22) && (ngContentIndex == 0))) { cb(this._text_23,ctx); }
  }
  handleEvent_14(eventName:string,$event:any):boolean {
    this.debug(14,9,4);
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._NgForm_14_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngSubmit')) {
      const pd_sub_0:any = ((<any>this.context.signup()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_16(eventName:string,$event:any):boolean {
    this.debug(16,10,6);
    this.compView_16.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdInput_16_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.profile.name = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_18(eventName:string,$event:any):boolean {
    this.debug(18,11,6);
    this.compView_18.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdInput_18_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.profile.email = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_20(eventName:string,$event:any):boolean {
    this.debug(20,12,6);
    this.compView_20.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdInput_20_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.profile.mission = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_22(eventName:string,$event:any):boolean {
    this.debug(22,13,6);
    this.compView_22.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdButton_22_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.signup()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}