/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['.profile_input {\n  width: 100%;\n}\n\n.profile_text {\n  width: 100%;\n  rows: 5;\n}\n\n.profile_button {\n  position: relative;\n  width: 100%;\n  background-color: darkcyan;\n  color: white;\n  margin-top: 2em!important;\n}\n'];