/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['\n.help_you {\n  position: relative;\n  min-width: 100px;\n  width: 30vw;\n  left: calc((100vw - 30vw)/2);\n  top: calc((100vh - 20vh)/4);\n}\n\n.invite_input {\n  width: 80%;\n}\n\n.invite_message {\n  width: 100%;\n}\n\n.invite_button {\n  position: relative;\n  width: 100%;\n  background-color: darkcyan;\n  color: white;\n  margin-top: 2em!important;\n}\n\n.invite_footer {\n  margin-top: 1.5em!important;\n}\n\n.content {\n  padding: 0;\n}\n'];