/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../app/components/invite/invite.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/debug_context';
import * as import3 from '../../../../app/services/profile.service';
import * as import4 from '../../../../app/services/invite.service';
import * as import5 from '@angular/core/src/render/api';
import * as import6 from '@angular/core/src/linker/view_utils';
import * as import7 from '@angular/core/src/metadata/view';
import * as import8 from '@angular/core/src/linker/view_type';
import * as import9 from '@angular/core/src/change_detection/change_detection';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from '@angular/http/src/http';
import * as import12 from '@angular/router/src/router';
import * as import13 from './invite.component.css';
import * as import14 from '@angular/material/card/card';
import * as import15 from '@angular/material/core/compatibility/style-compatibility';
import * as import16 from '@angular/material/input/input';
import * as import17 from '@angular/forms/src/directives/control_value_accessor';
import * as import18 from '@angular/forms/src/directives/ng_model';
import * as import19 from '@angular/forms/src/directives/ng_control';
import * as import20 from '@angular/forms/src/directives/ng_control_status';
import * as import21 from '@angular/material/button/button';
import * as import22 from '@angular/material/icon/icon';
import * as import23 from '@angular/material/list/list';
import * as import24 from '@angular/core/src/linker/template_ref';
import * as import25 from '@angular/common/src/directives/ng_for';
import * as import26 from '../../../node_modules/@angular/material/card/card.ngfactory';
import * as import27 from '../../../node_modules/@angular/material/core/compatibility/style-compatibility.ngfactory';
import * as import28 from '../../../node_modules/@angular/material/input/input.ngfactory';
import * as import29 from '../../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import30 from '../../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import31 from '@angular/core/src/linker/query_list';
import * as import32 from '../../../node_modules/@angular/material/button/button.ngfactory';
import * as import33 from '../../../node_modules/@angular/material/icon/icon.ngfactory';
import * as import34 from '../../../node_modules/@angular/material/list/list.ngfactory';
import * as import35 from '@angular/core/src/linker/view_container';
import * as import36 from '../../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import37 from '@angular/core/src/linker/element_ref';
import * as import38 from '@angular/material/icon/icon-registry';
import * as import39 from '@angular/core/src/change_detection/differs/iterable_differs';
export class Wrapper_InviteComponent {
  /*private*/ _eventHandler:Function;
  context:import0.InviteComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any,p2:any) {
    this._changed = false;
    this.context = new import0.InviteComponent(p0,p1,p2);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
  const nodeDebugInfos_InviteComponent_Host0:import2.StaticNodeDebugInfo[] = [new import2.StaticNodeDebugInfo([
    import3.ProfileService,
    import4.InviteService,
    import0.InviteComponent
  ]
,import0.InviteComponent,{})];
var renderType_InviteComponent_Host:import5.RenderComponentType = import6.createRenderComponentType('',0,import7.ViewEncapsulation.None,([] as any[]),{});
class View_InviteComponent_Host0 extends import1.DebugAppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.InviteComponent>;
  _ProfileService_0_3:import3.ProfileService;
  _InviteService_0_4:import4.InviteService;
  _InviteComponent_0_5:Wrapper_InviteComponent;
  constructor(viewUtils:import6.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_InviteComponent_Host0,renderType_InviteComponent_Host,import8.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import9.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_InviteComponent_Host0);
  }
  createInternal(rootSelector:string):import10.ComponentRef<any> {
    this._el_0 = import6.selectOrCreateRenderHostElement(this.renderer,'ng-component',import6.EMPTY_INLINE_ARRAY,rootSelector,this.debug(0,0,0));
    this.compView_0 = new View_InviteComponent0(this.viewUtils,this,0,this._el_0);
    this._ProfileService_0_3 = new import3.ProfileService(this.injectorGet(import11.Http,this.parentIndex));
    this._InviteService_0_4 = new import4.InviteService(this.injectorGet(import11.Http,this.parentIndex));
    this._InviteComponent_0_5 = new Wrapper_InviteComponent(this._ProfileService_0_3,this._InviteService_0_4,this.injectorGet(import12.Router,this.parentIndex));
    this.compView_0.create(this._InviteComponent_0_5.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import10.ComponentRef_<any>(0,this,this._el_0,this._InviteComponent_0_5.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.ProfileService) && (0 === requestNodeIndex))) { return this._ProfileService_0_3; }
    if (((token === import4.InviteService) && (0 === requestNodeIndex))) { return this._InviteService_0_4; }
    if (((token === import0.InviteComponent) && (0 === requestNodeIndex))) { return this._InviteComponent_0_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.debug(0,0,0);
    this._InviteComponent_0_5.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const InviteComponentNgFactory:import10.ComponentFactory<import0.InviteComponent> = new import10.ComponentFactory<import0.InviteComponent>('ng-component',View_InviteComponent_Host0,import0.InviteComponent);
const styles_InviteComponent:any[] = [import13.styles];
const nodeDebugInfos_InviteComponent0:import2.StaticNodeDebugInfo[] = [
  new import2.StaticNodeDebugInfo([
    import14.MdCard,
    import15.StyleCompatibility
  ]
  ,import14.MdCard,{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([
    import14.MdCardContent,
    import15.StyleCompatibility
  ]
  ,(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([
    import16.MdInput,
    import17.NG_VALUE_ACCESSOR,
    import18.NgModel,
    import19.NgControl,
    import20.NgControlStatus,
    import15.StyleCompatibility
  ]
  ,import16.MdInput,{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([import21.MdButton],import21.MdButton,{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([
    import22.MdIcon,
    import15.StyleCompatibility
  ]
  ,import22.MdIcon,{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([
    import23.MdList,
    import15.StyleCompatibility
  ]
  ,import23.MdList,{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([
    import24.TemplateRef,
    import25.NgFor
  ]
  ,(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([
    import16.MdInput,
    import17.NG_VALUE_ACCESSOR,
    import18.NgModel,
    import19.NgControl,
    import20.NgControlStatus
  ]
  ,import16.MdInput,{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([import21.MdButton],import21.MdButton,{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{})
]
;
var renderType_InviteComponent:import5.RenderComponentType = import6.createRenderComponentType('/Users/jessebowden/ichuwt/frontend/src/app/components/invite/invite.component.html',0,import7.ViewEncapsulation.None,styles_InviteComponent,{});
export class View_InviteComponent0 extends import1.DebugAppView<import0.InviteComponent> {
  _el_0:any;
  compView_0:import1.AppView<import14.MdCard>;
  _MdCard_0_3:import26.Wrapper_MdCard;
  _StyleCompatibility_0_4:import27.Wrapper_StyleCompatibility;
  _text_1:any;
  _el_2:any;
  _MdCardContent_2_3:import26.Wrapper_MdCardContent;
  _StyleCompatibility_2_4:import27.Wrapper_StyleCompatibility;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  compView_9:import1.AppView<import16.MdInput>;
  _MdInput_9_3:import28.Wrapper_MdInput;
  _NG_VALUE_ACCESSOR_9_4:any[];
  _NgModel_9_5:import29.Wrapper_NgModel;
  _NgControl_9_6:any;
  _NgControlStatus_9_7:import30.Wrapper_NgControlStatus;
  _StyleCompatibility_9_8:import27.Wrapper_StyleCompatibility;
  _query_MdPlaceholder_9_0:import31.QueryList<any>;
  _query_MdHint_9_1:import31.QueryList<any>;
  _text_10:any;
  _el_11:any;
  compView_11:import1.AppView<import21.MdButton>;
  _MdButton_11_3:import32.Wrapper_MdButton;
  _text_12:any;
  _el_13:any;
  compView_13:import1.AppView<import22.MdIcon>;
  _MdIcon_13_3:import33.Wrapper_MdIcon;
  _StyleCompatibility_13_4:import27.Wrapper_StyleCompatibility;
  _text_14:any;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  compView_17:import1.AppView<import23.MdList>;
  _MdList_17_3:import34.Wrapper_MdList;
  _StyleCompatibility_17_4:import27.Wrapper_StyleCompatibility;
  _text_18:any;
  _anchor_19:any;
  /*private*/ _vc_19:import35.ViewContainer;
  _TemplateRef_19_5:any;
  _NgFor_19_6:import36.Wrapper_NgFor;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  compView_22:import1.AppView<import16.MdInput>;
  _MdInput_22_3:import28.Wrapper_MdInput;
  _NG_VALUE_ACCESSOR_22_4:any[];
  _NgModel_22_5:import29.Wrapper_NgModel;
  _NgControl_22_6:any;
  _NgControlStatus_22_7:import30.Wrapper_NgControlStatus;
  _query_MdPlaceholder_22_0:import31.QueryList<any>;
  _query_MdHint_22_1:import31.QueryList<any>;
  _text_23:any;
  _el_24:any;
  compView_24:import1.AppView<import21.MdButton>;
  _MdButton_24_3:import32.Wrapper_MdButton;
  _text_25:any;
  _text_26:any;
  _text_27:any;
  _text_28:any;
  /*private*/ _expr_64:any;
  constructor(viewUtils:import6.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_InviteComponent0,renderType_InviteComponent,import8.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import9.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_InviteComponent0);
    this._expr_64 = import9.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import10.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import6.createRenderElement(this.renderer,parentRenderNode,'md-card',new import6.InlineArray4(4,'class','help_you','id','help_you'),this.debug(0,0,0));
    this.compView_0 = new import26.View_MdCard0(this.viewUtils,this,0,this._el_0);
    this._MdCard_0_3 = new import26.Wrapper_MdCard();
    this._StyleCompatibility_0_4 = new import27.Wrapper_StyleCompatibility(this.renderer,new import37.ElementRef(this._el_0));
    this._text_1 = this.renderer.createText((null as any),'\n  ',this.debug(1,0,40));
    this._el_2 = import6.createRenderElement(this.renderer,(null as any),'md-card-content',import6.EMPTY_INLINE_ARRAY,this.debug(2,1,2));
    this._MdCardContent_2_3 = new import26.Wrapper_MdCardContent();
    this._StyleCompatibility_2_4 = new import27.Wrapper_StyleCompatibility(this.renderer,new import37.ElementRef(this._el_2));
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',this.debug(3,1,19));
    this._el_4 = import6.createRenderElement(this.renderer,this._el_2,'img',new import6.InlineArray8(6,'class','content','md-card-image','','src','https://scontent.fbed1-2.fna.fbcdn.net/v/t1.0-9/15027882_10101666597237585_7556774340470305079_n.jpg?oh=635948e21d52a9aacc0ab9cc53a4e1ad&oe=58D120BD'),this.debug(4,2,4));
    this._text_5 = this.renderer.createText(this._el_2,'\n    ',this.debug(5,2,195));
    this._el_6 = import6.createRenderElement(this.renderer,this._el_2,'p',import6.EMPTY_INLINE_ARRAY,this.debug(6,3,4));
    this._text_7 = this.renderer.createText(this._el_6,'',this.debug(7,3,7));
    this._text_8 = this.renderer.createText(this._el_2,'\n    ',this.debug(8,4,39));
    this._el_9 = import6.createRenderElement(this.renderer,this._el_2,'md-input',new import6.InlineArray16(10,'align','start','class','invite_input','id','email_input','name','username','placeholder','E-Mail'),this.debug(9,5,4));
    this.compView_9 = new import28.View_MdInput0(this.viewUtils,this,9,this._el_9);
    this._MdInput_9_3 = new import28.Wrapper_MdInput(new import37.ElementRef(this._el_9));
    this._NG_VALUE_ACCESSOR_9_4 = [this._MdInput_9_3.context];
    this._NgModel_9_5 = new import29.Wrapper_NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_9_4);
    this._NgControl_9_6 = this._NgModel_9_5.context;
    this._NgControlStatus_9_7 = new import30.Wrapper_NgControlStatus(this._NgControl_9_6);
    this._StyleCompatibility_9_8 = new import27.Wrapper_StyleCompatibility(this.renderer,new import37.ElementRef(this._el_9));
    this._query_MdPlaceholder_9_0 = new import31.QueryList<any>();
    this._query_MdHint_9_1 = new import31.QueryList<any>();
    this._query_MdPlaceholder_9_0.reset(([] as any[]));
    this._MdInput_9_3.context._placeholderChild = this._query_MdPlaceholder_9_0.first;
    this.compView_9.create(this._MdInput_9_3.context);
    this._text_10 = this.renderer.createText(this._el_2,'\n    ',this.debug(10,5,165));
    this._el_11 = import6.createRenderElement(this.renderer,this._el_2,'button',new import6.InlineArray4(4,'md-mini-fab','','style','background-color: darkcyan; color: white;'),this.debug(11,6,4));
    this.compView_11 = new import32.View_MdButton0(this.viewUtils,this,11,this._el_11);
    this._MdButton_11_3 = new import32.Wrapper_MdButton(new import37.ElementRef(this._el_11),this.renderer);
    this._text_12 = this.renderer.createText((null as any),'\n      ',this.debug(12,6,95));
    this._el_13 = import6.createRenderElement(this.renderer,(null as any),'md-icon',new import6.InlineArray4(4,'class','md-24','role','img'),this.debug(13,7,6));
    this.compView_13 = new import33.View_MdIcon0(this.viewUtils,this,13,this._el_13);
    this._MdIcon_13_3 = new import33.Wrapper_MdIcon(new import37.ElementRef(this._el_13),this.renderer,this.parentView.injectorGet(import38.MdIconRegistry,this.parentIndex));
    this._StyleCompatibility_13_4 = new import27.Wrapper_StyleCompatibility(this.renderer,new import37.ElementRef(this._el_13));
    this._text_14 = this.renderer.createText((null as any),'+',this.debug(14,7,29));
    this.compView_13.create(this._MdIcon_13_3.context);
    this._text_15 = this.renderer.createText((null as any),'\n    ',this.debug(15,7,40));
    this.compView_11.create(this._MdButton_11_3.context);
    this._text_16 = this.renderer.createText(this._el_2,'\n\n      ',this.debug(16,8,13));
    this._el_17 = import6.createRenderElement(this.renderer,this._el_2,'md-list',new import6.InlineArray2(2,'role','list'),this.debug(17,10,6));
    this.compView_17 = new import34.View_MdList0(this.viewUtils,this,17,this._el_17);
    this._MdList_17_3 = new import34.Wrapper_MdList();
    this._StyleCompatibility_17_4 = new import27.Wrapper_StyleCompatibility(this.renderer,new import37.ElementRef(this._el_17));
    this._text_18 = this.renderer.createText((null as any),'\n        ',this.debug(18,10,15));
    this._anchor_19 = this.renderer.createTemplateAnchor((null as any),this.debug(19,11,8));
    this._vc_19 = new import35.ViewContainer(19,17,this,this._anchor_19);
    this._TemplateRef_19_5 = new import24.TemplateRef_(this,19,this._anchor_19);
    this._NgFor_19_6 = new import36.Wrapper_NgFor(this._vc_19.vcRef,this._TemplateRef_19_5,this.parentView.injectorGet(import39.IterableDiffers,this.parentIndex),this.ref);
    this._text_20 = this.renderer.createText((null as any),'\n      ',this.debug(20,11,86));
    this.compView_17.create(this._MdList_17_3.context);
    this._text_21 = this.renderer.createText(this._el_2,'\n\n      ',this.debug(21,12,16));
    this._el_22 = import6.createRenderElement(this.renderer,this._el_2,'md-textarea',new import6.InlineArray8(8,'class','invite_message','placeholder','E-Mail Text','rows','5','value',''),this.debug(22,14,6));
    this.compView_22 = new import28.View_MdInput0(this.viewUtils,this,22,this._el_22);
    this._MdInput_22_3 = new import28.Wrapper_MdInput(new import37.ElementRef(this._el_22));
    this._NG_VALUE_ACCESSOR_22_4 = [this._MdInput_22_3.context];
    this._NgModel_22_5 = new import29.Wrapper_NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_22_4);
    this._NgControl_22_6 = this._NgModel_22_5.context;
    this._NgControlStatus_22_7 = new import30.Wrapper_NgControlStatus(this._NgControl_22_6);
    this._query_MdPlaceholder_22_0 = new import31.QueryList<any>();
    this._query_MdHint_22_1 = new import31.QueryList<any>();
    this._query_MdPlaceholder_22_0.reset(([] as any[]));
    this._MdInput_22_3.context._placeholderChild = this._query_MdPlaceholder_22_0.first;
    this.compView_22.create(this._MdInput_22_3.context);
    this._text_23 = this.renderer.createText(this._el_2,'\n      ',this.debug(23,14,133));
    this._el_24 = import6.createRenderElement(this.renderer,this._el_2,'button',new import6.InlineArray8(8,'class','invite_button','md-button','','style','color: white;','type','submit'),this.debug(24,15,6));
    this.compView_24 = new import32.View_MdButton0(this.viewUtils,this,24,this._el_24);
    this._MdButton_24_3 = new import32.Wrapper_MdButton(new import37.ElementRef(this._el_24),this.renderer);
    this._text_25 = this.renderer.createText((null as any),'Send Invites',this.debug(25,15,101));
    this.compView_24.create(this._MdButton_24_3.context);
    this._text_26 = this.renderer.createText(this._el_2,'\n\n  ',this.debug(26,15,122));
    this._text_27 = this.renderer.createText((null as any),'\n',this.debug(27,17,20));
    this.compView_0.create(this._MdCard_0_3.context);
    this._text_28 = this.renderer.createText(parentRenderNode,'\n',this.debug(28,18,10));
    var disposable_0:Function = import6.subscribeToRenderElement(this,this._el_9,new import6.InlineArray8(6,'keyup',(null as any),'ngModelChange',(null as any),'click',(null as any)),this.eventHandler(this.handleEvent_9));
    this._NgModel_9_5.subscribe(this,this.eventHandler(this.handleEvent_9),true);
    var disposable_1:Function = import6.subscribeToRenderElement(this,this._el_11,new import6.InlineArray8(8,'click',(null as any),'mousedown',(null as any),'focus',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_11));
    var disposable_2:Function = import6.subscribeToRenderElement(this,this._el_22,new import6.InlineArray4(4,'ngModelChange',(null as any),'click',(null as any)),this.eventHandler(this.handleEvent_22));
    this._NgModel_22_5.subscribe(this,this.eventHandler(this.handleEvent_22),true);
    var disposable_3:Function = import6.subscribeToRenderElement(this,this._el_24,new import6.InlineArray8(8,'click',(null as any),'mousedown',(null as any),'focus',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_24));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._anchor_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._text_26,
      this._text_27,
      this._text_28
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import16.MdInput) && (9 === requestNodeIndex))) { return this._MdInput_9_3.context; }
    if (((token === import17.NG_VALUE_ACCESSOR) && (9 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_9_4; }
    if (((token === import18.NgModel) && (9 === requestNodeIndex))) { return this._NgModel_9_5.context; }
    if (((token === import19.NgControl) && (9 === requestNodeIndex))) { return this._NgControl_9_6; }
    if (((token === import20.NgControlStatus) && (9 === requestNodeIndex))) { return this._NgControlStatus_9_7.context; }
    if (((token === import15.StyleCompatibility) && (9 === requestNodeIndex))) { return this._StyleCompatibility_9_8.context; }
    if (((token === import22.MdIcon) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._MdIcon_13_3.context; }
    if (((token === import15.StyleCompatibility) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._StyleCompatibility_13_4.context; }
    if (((token === import21.MdButton) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 15)))) { return this._MdButton_11_3.context; }
    if (((token === import24.TemplateRef) && (19 === requestNodeIndex))) { return this._TemplateRef_19_5; }
    if (((token === import25.NgFor) && (19 === requestNodeIndex))) { return this._NgFor_19_6.context; }
    if (((token === import23.MdList) && ((17 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._MdList_17_3.context; }
    if (((token === import15.StyleCompatibility) && ((17 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._StyleCompatibility_17_4.context; }
    if (((token === import16.MdInput) && (22 === requestNodeIndex))) { return this._MdInput_22_3.context; }
    if (((token === import17.NG_VALUE_ACCESSOR) && (22 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_22_4; }
    if (((token === import18.NgModel) && (22 === requestNodeIndex))) { return this._NgModel_22_5.context; }
    if (((token === import19.NgControl) && (22 === requestNodeIndex))) { return this._NgControl_22_6; }
    if (((token === import20.NgControlStatus) && (22 === requestNodeIndex))) { return this._NgControlStatus_22_7.context; }
    if (((token === import21.MdButton) && ((24 <= requestNodeIndex) && (requestNodeIndex <= 25)))) { return this._MdButton_24_3.context; }
    if (((token === import14.MdCardContent) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._MdCardContent_2_3.context; }
    if (((token === import15.StyleCompatibility) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._StyleCompatibility_2_4.context; }
    if (((token === import14.MdCard) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._MdCard_0_3.context; }
    if (((token === import15.StyleCompatibility) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._StyleCompatibility_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.debug(0,0,0);
    if (this._MdCard_0_3.ngDoCheck(this,this._el_0,throwOnChange)) { this.compView_0.markAsCheckOnce(); }
    this._StyleCompatibility_0_4.ngDoCheck(this,this._el_0,throwOnChange);
    this.debug(2,1,2);
    this._MdCardContent_2_3.ngDoCheck(this,this._el_2,throwOnChange);
    this._StyleCompatibility_2_4.ngDoCheck(this,this._el_2,throwOnChange);
    this.debug(9,5,66);
    const currVal_9_0_0:any = 'start';
    this._MdInput_9_3.check_align(currVal_9_0_0,throwOnChange,false);
    this.debug(9,5,80);
    const currVal_9_0_1:any = 'email_input';
    this._MdInput_9_3.check_id(currVal_9_0_1,throwOnChange,false);
    this.debug(9,5,14);
    const currVal_9_0_2:any = 'E-Mail';
    this._MdInput_9_3.check_placeholder(currVal_9_0_2,throwOnChange,false);
    this.debug(9,5,97);
    const currVal_9_0_3:any = 'username';
    this._MdInput_9_3.check_name(currVal_9_0_3,throwOnChange,false);
    this._MdInput_9_3.ngDoCheck(this,this._el_9,throwOnChange);
    this.debug(9,5,97);
    const currVal_9_1_0:any = 'username';
    this._NgModel_9_5.check_name(currVal_9_1_0,throwOnChange,false);
    this.debug(9,5,134);
    const currVal_9_1_1:any = this.context.email;
    this._NgModel_9_5.check_model(currVal_9_1_1,throwOnChange,false);
    this._NgModel_9_5.ngDoCheck(this,this._el_9,throwOnChange);
    this.debug(9,5,4);
    this._NgControlStatus_9_7.ngDoCheck(this,this._el_9,throwOnChange);
    this._StyleCompatibility_9_8.ngDoCheck(this,this._el_9,throwOnChange);
    this.debug(11,6,4);
    if (this._MdButton_11_3.ngDoCheck(this,this._el_11,throwOnChange)) { this.compView_11.markAsCheckOnce(); }
    this.debug(13,7,6);
    if (this._MdIcon_13_3.ngDoCheck(this,this._el_13,throwOnChange)) { this.compView_13.markAsCheckOnce(); }
    this._StyleCompatibility_13_4.ngDoCheck(this,this._el_13,throwOnChange);
    this.debug(17,10,6);
    this._MdList_17_3.ngDoCheck(this,this._el_17,throwOnChange);
    this._StyleCompatibility_17_4.ngDoCheck(this,this._el_17,throwOnChange);
    this.debug(19,11,22);
    const currVal_19_0_0:any = this.context.invitation.emails;
    this._NgFor_19_6.check_ngForOf(currVal_19_0_0,throwOnChange,false);
    this._NgFor_19_6.ngDoCheck(this,this._anchor_19,throwOnChange);
    this.debug(22,14,42);
    const currVal_22_0_0:any = 'E-Mail Text';
    this._MdInput_22_3.check_placeholder(currVal_22_0_0,throwOnChange,false);
    this.debug(22,14,110);
    const currVal_22_0_1:any = '5';
    this._MdInput_22_3.check_rows(currVal_22_0_1,throwOnChange,false);
    this.debug(22,14,68);
    const currVal_22_0_2:any = '';
    this._MdInput_22_3.check_value(currVal_22_0_2,throwOnChange,false);
    this._MdInput_22_3.ngDoCheck(this,this._el_22,throwOnChange);
    this.debug(22,14,77);
    const currVal_22_1_0:any = this.context.invitation.message;
    this._NgModel_22_5.check_model(currVal_22_1_0,throwOnChange,false);
    this._NgModel_22_5.ngDoCheck(this,this._el_22,throwOnChange);
    this.debug(22,14,6);
    this._NgControlStatus_22_7.ngDoCheck(this,this._el_22,throwOnChange);
    this.debug(24,15,6);
    if (this._MdButton_24_3.ngDoCheck(this,this._el_24,throwOnChange)) { this.compView_24.markAsCheckOnce(); }
    this._vc_19.detectChangesInNestedViews(throwOnChange);
    if (!throwOnChange) {
      if (this._query_MdHint_9_1.dirty) {
        this._query_MdHint_9_1.reset(([] as any[]));
        this._MdInput_9_3.context._hintChildren = this._query_MdHint_9_1;
        this._query_MdHint_9_1.notifyOnChanges();
      }
      if (this._query_MdHint_22_1.dirty) {
        this._query_MdHint_22_1.reset(([] as any[]));
        this._MdInput_22_3.context._hintChildren = this._query_MdHint_22_1;
        this._query_MdHint_22_1.notifyOnChanges();
      }
      this.debug(9,5,4);
      if ((this.numberOfChecks === 0)) { this._MdInput_9_3.context.ngAfterContentInit(); }
      this.debug(22,14,6);
      if ((this.numberOfChecks === 0)) { this._MdInput_22_3.context.ngAfterContentInit(); }
    }
    this.debug(7,3,7);
    const currVal_64:any = import6.inlineInterpolate(1,'\n      Invites - ',this.context.profile.invites,'');
    if (import6.checkBinding(throwOnChange,this._expr_64,currVal_64)) {
      this.renderer.setText(this._text_7,currVal_64);
      this._expr_64 = currVal_64;
    }
    this._MdInput_9_3.checkHost(this,this.compView_9,this._el_9,throwOnChange);
    this._NgControlStatus_9_7.checkHost(this,this.compView_9,this._el_9,throwOnChange);
    this._MdButton_11_3.checkHost(this,this.compView_11,this._el_11,throwOnChange);
    this._MdInput_22_3.checkHost(this,this.compView_22,this._el_22,throwOnChange);
    this._NgControlStatus_22_7.checkHost(this,this.compView_22,this._el_22,throwOnChange);
    this._MdButton_24_3.checkHost(this,this.compView_24,this._el_24,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
    this.compView_9.detectChanges(throwOnChange);
    this.compView_11.detectChanges(throwOnChange);
    this.compView_13.detectChanges(throwOnChange);
    this.compView_17.detectChanges(throwOnChange);
    this.compView_22.detectChanges(throwOnChange);
    this.compView_24.detectChanges(throwOnChange);
    if (!throwOnChange) {
      this.debug(13,7,6);
      this._MdIcon_13_3.context.ngAfterViewChecked();
    }
  }
  destroyInternal():void {
    this._vc_19.destroyNestedViews();
    this.compView_0.destroy();
    this.compView_9.destroy();
    this.compView_11.destroy();
    this.compView_13.destroy();
    this.compView_17.destroy();
    this.compView_22.destroy();
    this.compView_24.destroy();
    this._MdInput_9_3.ngOnDestroy();
    this._NgModel_9_5.ngOnDestroy();
    this.debug(9,5,4);
    this.debug(13,7,6);
    this.debug(11,6,4);
    this.debug(19,11,8);
    this.debug(17,10,6);
    this._MdInput_22_3.ngOnDestroy();
    this._NgModel_22_5.ngOnDestroy();
    this.debug(22,14,6);
    this.debug(24,15,6);
    this.debug(2,1,2);
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 0) && (ngContentIndex == 0))) {
      cb(this._text_1,ctx);
      cb(this._el_2,ctx);
      cb(this._text_27,ctx);
    }
    if (((nodeIndex == 9) && (ngContentIndex == 0))) {  }
    if (((nodeIndex == 9) && (ngContentIndex == 1))) {  }
    if (((nodeIndex == 9) && (ngContentIndex == 2))) {  }
    if (((nodeIndex == 9) && (ngContentIndex == 3))) {  }
    if (((nodeIndex == 11) && (ngContentIndex == 0))) {
      cb(this._text_12,ctx);
      cb(this._el_13,ctx);
      cb(this._text_15,ctx);
    }
    if (((nodeIndex == 13) && (ngContentIndex == 0))) { cb(this._text_14,ctx); }
    if (((nodeIndex == 17) && (ngContentIndex == 0))) {
      cb(this._text_18,ctx);
      cb(this._vc_19.nativeElement,ctx);
      this._vc_19.visitNestedViewRootNodes(cb,ctx);
      cb(this._text_20,ctx);
    }
    if (((nodeIndex == 22) && (ngContentIndex == 0))) {  }
    if (((nodeIndex == 22) && (ngContentIndex == 1))) {  }
    if (((nodeIndex == 22) && (ngContentIndex == 2))) {  }
    if (((nodeIndex == 22) && (ngContentIndex == 3))) {  }
    if (((nodeIndex == 24) && (ngContentIndex == 0))) { cb(this._text_25,ctx); }
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 19)) { return new View_InviteComponent1(this.viewUtils,this,19,this._anchor_19,this._vc_19); }
    return (null as any);
  }
  handleEvent_9(eventName:string,$event:any):boolean {
    this.debug(9,5,4);
    this.compView_9.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdInput_9_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'keyup')) {
      const pd_sub_0:any = ((<any>this.context.eventHandler($event)) !== false);
      result = (pd_sub_0 && result);
    }
    if ((eventName == 'ngModelChange')) {
      const pd_sub_1:any = ((<any>(this.context.email = $event)) !== false);
      result = (pd_sub_1 && result);
    }
    return result;
  }
  handleEvent_11(eventName:string,$event:any):boolean {
    this.debug(11,6,4);
    this.compView_11.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdButton_11_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.addEmail()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_22(eventName:string,$event:any):boolean {
    this.debug(22,14,6);
    this.compView_22.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdInput_22_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.invitation.message = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_24(eventName:string,$event:any):boolean {
    this.debug(24,15,6);
    this.compView_24.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdButton_24_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.invite()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
const nodeDebugInfos_InviteComponent1:import2.StaticNodeDebugInfo[] = [
  new import2.StaticNodeDebugInfo([
    import23.MdListItem,
    import15.StyleCompatibility
  ]
  ,import23.MdListItem,{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{})
]
;
class View_InviteComponent1 extends import1.DebugAppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import23.MdListItem>;
  _MdListItem_0_3:import34.Wrapper_MdListItem;
  _StyleCompatibility_0_4:import27.Wrapper_StyleCompatibility;
  _query_MdLine_0_0:import31.QueryList<any>;
  _query_MdListAvatar_0_1:import31.QueryList<any>;
  _text_1:any;
  /*private*/ _expr_7:any;
  constructor(viewUtils:import6.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import35.ViewContainer) {
    super(View_InviteComponent1,renderType_InviteComponent,import8.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import9.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_InviteComponent1,declaredViewContainer);
    this._expr_7 = import9.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import10.ComponentRef<any> {
    this._el_0 = import6.createRenderElement(this.renderer,(null as any),'md-list-item',new import6.InlineArray2(2,'role','listitem'),this.debug(0,11,8));
    this.compView_0 = new import34.View_MdListItem0(this.viewUtils,this,0,this._el_0);
    this._MdListItem_0_3 = new import34.Wrapper_MdListItem(this.renderer,new import37.ElementRef(this._el_0));
    this._StyleCompatibility_0_4 = new import27.Wrapper_StyleCompatibility(this.renderer,new import37.ElementRef(this._el_0));
    this._query_MdLine_0_0 = new import31.QueryList<any>();
    this._query_MdListAvatar_0_1 = new import31.QueryList<any>();
    this._text_1 = this.renderer.createText((null as any),'',this.debug(1,11,62));
    this._query_MdListAvatar_0_1.reset(([] as any[]));
    this._MdListItem_0_3.context._hasAvatar = this._query_MdListAvatar_0_1.first;
    this.compView_0.create(this._MdListItem_0_3.context);
    var disposable_0:Function = import6.subscribeToRenderElement(this,this._el_0,new import6.InlineArray4(4,'focus',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_0));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import23.MdListItem) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._MdListItem_0_3.context; }
    if (((token === import15.StyleCompatibility) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._StyleCompatibility_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.debug(0,11,8);
    this._MdListItem_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this._StyleCompatibility_0_4.ngDoCheck(this,this._el_0,throwOnChange);
    if (!throwOnChange) {
      if (this._query_MdLine_0_0.dirty) {
        this._query_MdLine_0_0.reset(([] as any[]));
        this._MdListItem_0_3.context._lines = this._query_MdLine_0_0;
        this._query_MdLine_0_0.notifyOnChanges();
      }
      this.debug(0,11,8);
      if ((this.numberOfChecks === 0)) { this._MdListItem_0_3.context.ngAfterContentInit(); }
    }
    this.debug(1,11,62);
    const currVal_7:any = import6.inlineInterpolate(1,'',this.context.$implicit,'');
    if (import6.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setText(this._text_1,currVal_7);
      this._expr_7 = currVal_7;
    }
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 0) && (ngContentIndex == 0))) {  }
    if (((nodeIndex == 0) && (ngContentIndex == 1))) {  }
    if (((nodeIndex == 0) && (ngContentIndex == 2))) { cb(this._text_1,ctx); }
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.debug(0,11,8);
    this.compView_0.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdListItem_0_3.handleEvent(eventName,$event) && result);
    return result;
  }
}