apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    name: backend
    env: production
    role: proxy
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
      name: backend