apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    name: frontend
    env: production
    role: proxy
spec:
  type: NodePort
  ports:
      - port: 443
        name: https
        targetPort: 3002
        protocol: TCP
      - port: 80
        name: http
        targetPort: 3001
        protocol: TCP
  selector:
    name: frontend
