/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../app/app.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/core/src/application_module';
import * as import4 from '@angular/platform-browser/src/browser';
import * as import5 from '@angular/forms/src/directives';
import * as import6 from '@angular/forms/src/form_providers';
import * as import7 from '@angular/http/src/http_module';
import * as import8 from '@angular/material/core/ripple/ripple';
import * as import9 from '@angular/material/button/button';
import * as import10 from '@angular/material/card/card';
import * as import11 from '@angular/material/checkbox/checkbox';
import * as import12 from '@angular/material/core/line/line';
import * as import13 from '@angular/material/grid-list/grid-list';
import * as import14 from '@angular/material/input/input';
import * as import15 from '@angular/material/list/list';
import * as import16 from '@angular/material/progress-bar/progress-bar';
import * as import17 from '@angular/material/progress-circle/progress-circle';
import * as import18 from '@angular/material/sidenav/sidenav';
import * as import19 from '@angular/material/core/portal/portal-directives';
import * as import20 from '@angular/material/tabs/tabs';
import * as import21 from '@angular/material/toolbar/toolbar';
import * as import22 from '@angular/material/core/rtl/dir';
import * as import23 from '@angular/material/core/a11y/index';
import * as import24 from '@angular/material/button-toggle/button-toggle';
import * as import25 from '@angular/material/core/overlay/overlay-directives';
import * as import26 from '@angular/material/dialog/dialog';
import * as import27 from '@angular/material/icon/icon';
import * as import28 from '@angular/material/menu/menu';
import * as import29 from '@angular/material/radio/radio';
import * as import30 from '@angular/material/slider/slider';
import * as import31 from '@angular/material/slide-toggle/slide-toggle';
import * as import32 from '@angular/material/snack-bar/snack-bar';
import * as import33 from '@angular/material/tooltip/tooltip';
import * as import34 from '@angular/material/core/compatibility/style-compatibility';
import * as import35 from '@angular/material/module';
import * as import36 from '@angular/router/src/router_module';
import * as import37 from '@angular/common/src/localization';
import * as import38 from '@angular/core/src/application_init';
import * as import39 from '@angular/core/src/testability/testability';
import * as import40 from '@angular/core/src/application_ref';
import * as import41 from '@angular/core/src/linker/compiler';
import * as import42 from '@angular/material/core/gestures/MdGestureConfig';
import * as import43 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import44 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import45 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import46 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import47 from '@angular/core/src/linker/view_utils';
import * as import48 from '@angular/platform-browser/src/browser/title';
import * as import49 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import50 from '@angular/http/src/backends/browser_xhr';
import * as import51 from '@angular/http/src/base_response_options';
import * as import52 from '@angular/http/src/backends/xhr_backend';
import * as import53 from '@angular/http/src/base_request_options';
import * as import54 from '@angular/material/core/a11y/live-announcer';
import * as import55 from '@angular/material/core/a11y/interactivity-checker';
import * as import56 from '@angular/material/core/coordination/unique-selection-dispatcher';
import * as import57 from '@angular/material/core/overlay/overlay-container';
import * as import58 from '@angular/material/core/overlay/position/viewport-ruler';
import * as import59 from '@angular/material/core/overlay/position/overlay-position-builder';
import * as import60 from '@angular/material/core/overlay/overlay';
import * as import61 from '@angular/material/icon/icon-registry';
import * as import62 from '@angular/common/src/location/location';
import * as import63 from '@angular/router/src/url_tree';
import * as import64 from '@angular/router/src/router_outlet_map';
import * as import65 from '@angular/core/src/linker/system_js_ng_module_factory_loader';
import * as import66 from '@angular/router/src/router_preloader';
import * as import67 from '@angular/core/src/di/injector';
import * as import68 from '../node_modules/@angular/material/dialog/dialog-container.ngfactory';
import * as import69 from '../node_modules/@angular/material/snack-bar/snack-bar-container.ngfactory';
import * as import70 from '../node_modules/@angular/material/snack-bar/simple-snack-bar.ngfactory';
import * as import71 from '../node_modules/@angular/material/tooltip/tooltip.ngfactory';
import * as import72 from './app.component.ngfactory';
import * as import73 from './components/login/login.component.ngfactory';
import * as import74 from './components/dashboard/dashboard.component.ngfactory';
import * as import75 from './components/invite/invite.component.ngfactory';
import * as import76 from './components/signup/signup.component.ngfactory';
import * as import77 from './components/profile/profile.component.ngfactory';
import * as import78 from '@angular/core/src/application_tokens';
import * as import79 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import80 from '@angular/platform-browser/src/dom/events/key_events';
import * as import81 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import82 from '@angular/core/src/zone/ng_zone';
import * as import83 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import84 from '@angular/common/src/location/platform_location';
import * as import85 from '@angular/common/src/location/location_strategy';
import * as import86 from '../../app/app.component';
import * as import87 from '../../app/components/login/login.component';
import * as import88 from '../../app/components/dashboard/dashboard.component';
import * as import89 from '../../app/components/invite/invite.component';
import * as import90 from '../../app/components/signup/signup.component';
import * as import91 from '../../app/components/profile/profile.component';
import * as import92 from '@angular/router/src/url_handling_strategy';
import * as import93 from '@angular/router/src/router';
import * as import94 from '@angular/core/src/console';
import * as import95 from '@angular/core/src/i18n/tokens';
import * as import96 from '@angular/core/src/error_handler';
import * as import97 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import98 from '@angular/platform-browser/src/dom/animation_driver';
import * as import99 from '@angular/core/src/render/api';
import * as import100 from '@angular/core/src/security';
import * as import101 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import102 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import103 from '@angular/http/src/interfaces';
import * as import104 from '@angular/http/src/http';
import * as import105 from '@angular/core/src/linker/ng_module_factory_loader';
import * as import106 from '@angular/router/src/router_config_loader';
import * as import107 from '@angular/router/src/router_state';
class AppModuleInjector extends import0.NgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import3.ApplicationModule;
  _BrowserModule_2:import4.BrowserModule;
  _InternalFormsSharedModule_3:import5.InternalFormsSharedModule;
  _FormsModule_4:import6.FormsModule;
  _HttpModule_5:import7.HttpModule;
  _MdRippleModule_6:import8.MdRippleModule;
  _MdButtonModule_7:import9.MdButtonModule;
  _MdCardModule_8:import10.MdCardModule;
  _MdCheckboxModule_9:import11.MdCheckboxModule;
  _MdLineModule_10:import12.MdLineModule;
  _MdGridListModule_11:import13.MdGridListModule;
  _MdInputModule_12:import14.MdInputModule;
  _MdListModule_13:import15.MdListModule;
  _MdProgressBarModule_14:import16.MdProgressBarModule;
  _MdProgressCircleModule_15:import17.MdProgressCircleModule;
  _MdSidenavModule_16:import18.MdSidenavModule;
  _PortalModule_17:import19.PortalModule;
  _MdTabsModule_18:import20.MdTabsModule;
  _MdToolbarModule_19:import21.MdToolbarModule;
  _RtlModule_20:import22.RtlModule;
  _A11yModule_21:import23.A11yModule;
  _MdButtonToggleModule_22:import24.MdButtonToggleModule;
  _OverlayModule_23:import25.OverlayModule;
  _MdDialogModule_24:import26.MdDialogModule;
  _MdIconModule_25:import27.MdIconModule;
  _MdMenuModule_26:import28.MdMenuModule;
  _MdRadioModule_27:import29.MdRadioModule;
  _MdSliderModule_28:import30.MdSliderModule;
  _MdSlideToggleModule_29:import31.MdSlideToggleModule;
  _MdSnackBarModule_30:import32.MdSnackBarModule;
  _MdTooltipModule_31:import33.MdTooltipModule;
  _StyleCompatibilityModule_32:import34.StyleCompatibilityModule;
  _MaterialRootModule_33:import35.MaterialRootModule;
  _ROUTER_FORROOT_GUARD_34:any;
  _RouterModule_35:import36.RouterModule;
  _AppModule_36:import1.AppModule;
  __LOCALE_ID_37:any;
  __NgLocalization_38:import37.NgLocaleLocalization;
  _ErrorHandler_39:any;
  _ApplicationInitStatus_40:import38.ApplicationInitStatus;
  _Testability_41:import39.Testability;
  _ApplicationRef__42:import40.ApplicationRef_;
  __ApplicationRef_43:any;
  __Compiler_44:import41.Compiler;
  __APP_ID_45:any;
  __DOCUMENT_46:any;
  __HAMMER_GESTURE_CONFIG_47:import42.MdGestureConfig;
  __EVENT_MANAGER_PLUGINS_48:any[];
  __EventManager_49:import43.EventManager;
  __DomSharedStylesHost_50:import44.DomSharedStylesHost;
  __AnimationDriver_51:any;
  __DomRootRenderer_52:import45.DomRootRenderer_;
  __RootRenderer_53:any;
  __DomSanitizer_54:import46.DomSanitizerImpl;
  __Sanitizer_55:any;
  __ViewUtils_56:import47.ViewUtils;
  __IterableDiffers_57:any;
  __KeyValueDiffers_58:any;
  __SharedStylesHost_59:any;
  __Title_60:import48.Title;
  __RadioControlRegistry_61:import49.RadioControlRegistry;
  __BrowserXhr_62:import50.BrowserXhr;
  __ResponseOptions_63:import51.BaseResponseOptions;
  __XSRFStrategy_64:any;
  __XHRBackend_65:import52.XHRBackend;
  __RequestOptions_66:import53.BaseRequestOptions;
  __Http_67:any;
  __MdLiveAnnouncer_68:import54.MdLiveAnnouncer;
  __InteractivityChecker_69:import55.InteractivityChecker;
  __MdUniqueSelectionDispatcher_70:import56.MdUniqueSelectionDispatcher;
  __OverlayContainer_71:import57.OverlayContainer;
  __ViewportRuler_72:import58.ViewportRuler;
  __OverlayPositionBuilder_73:import59.OverlayPositionBuilder;
  __Overlay_74:import60.Overlay;
  __MdDialog_75:import26.MdDialog;
  __MdIconRegistry_76:import61.MdIconRegistry;
  __MdSnackBar_77:import32.MdSnackBar;
  __ROUTER_CONFIGURATION_78:any;
  __LocationStrategy_79:any;
  __Location_80:import62.Location;
  __UrlSerializer_81:import63.DefaultUrlSerializer;
  __RouterOutletMap_82:import64.RouterOutletMap;
  __NgModuleFactoryLoader_83:import65.SystemJsNgModuleLoader;
  __ROUTES_84:any[];
  __Router_85:any;
  __ActivatedRoute_86:any;
  _NoPreloading_87:import66.NoPreloading;
  _PreloadingStrategy_88:any;
  _RouterPreloader_89:import66.RouterPreloader;
  __PreloadAllModules_90:import66.PreloadAllModules;
  __ROUTER_INITIALIZER_91:any;
  __APP_BOOTSTRAP_LISTENER_92:any[];
  constructor(parent:import67.Injector) {
    super(parent,[
      import68.MdDialogContainerNgFactory,
      import69.MdSnackBarContainerNgFactory,
      import70.SimpleSnackBarNgFactory,
      import71.TooltipComponentNgFactory,
      import72.AppComponentNgFactory,
      import73.LoginComponentNgFactory,
      import74.DashboardComponentNgFactory,
      import75.InviteComponentNgFactory,
      import76.SignupComponentNgFactory,
      import77.ProfileComponentNgFactory,
      import72.AppComponentNgFactory
    ]
    ,[import72.AppComponentNgFactory]);
  }
  get _LOCALE_ID_37():any {
    if ((this.__LOCALE_ID_37 == null)) { (this.__LOCALE_ID_37 = 'en-US'); }
    return this.__LOCALE_ID_37;
  }
  get _NgLocalization_38():import37.NgLocaleLocalization {
    if ((this.__NgLocalization_38 == null)) { (this.__NgLocalization_38 = new import37.NgLocaleLocalization(this._LOCALE_ID_37)); }
    return this.__NgLocalization_38;
  }
  get _ApplicationRef_43():any {
    if ((this.__ApplicationRef_43 == null)) { (this.__ApplicationRef_43 = this._ApplicationRef__42); }
    return this.__ApplicationRef_43;
  }
  get _Compiler_44():import41.Compiler {
    if ((this.__Compiler_44 == null)) { (this.__Compiler_44 = new import41.Compiler()); }
    return this.__Compiler_44;
  }
  get _APP_ID_45():any {
    if ((this.__APP_ID_45 == null)) { (this.__APP_ID_45 = import78._appIdRandomProviderFactory()); }
    return this.__APP_ID_45;
  }
  get _DOCUMENT_46():any {
    if ((this.__DOCUMENT_46 == null)) { (this.__DOCUMENT_46 = import4._document()); }
    return this.__DOCUMENT_46;
  }
  get _HAMMER_GESTURE_CONFIG_47():import42.MdGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_47 == null)) { (this.__HAMMER_GESTURE_CONFIG_47 = new import42.MdGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_47;
  }
  get _EVENT_MANAGER_PLUGINS_48():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_48 == null)) { (this.__EVENT_MANAGER_PLUGINS_48 = [
      new import79.DomEventsPlugin(),
      new import80.KeyEventsPlugin(),
      new import81.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_47)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_48;
  }
  get _EventManager_49():import43.EventManager {
    if ((this.__EventManager_49 == null)) { (this.__EventManager_49 = new import43.EventManager(this._EVENT_MANAGER_PLUGINS_48,this.parent.get(import82.NgZone))); }
    return this.__EventManager_49;
  }
  get _DomSharedStylesHost_50():import44.DomSharedStylesHost {
    if ((this.__DomSharedStylesHost_50 == null)) { (this.__DomSharedStylesHost_50 = new import44.DomSharedStylesHost(this._DOCUMENT_46)); }
    return this.__DomSharedStylesHost_50;
  }
  get _AnimationDriver_51():any {
    if ((this.__AnimationDriver_51 == null)) { (this.__AnimationDriver_51 = import4._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_51;
  }
  get _DomRootRenderer_52():import45.DomRootRenderer_ {
    if ((this.__DomRootRenderer_52 == null)) { (this.__DomRootRenderer_52 = new import45.DomRootRenderer_(this._DOCUMENT_46,this._EventManager_49,this._DomSharedStylesHost_50,this._AnimationDriver_51,this._APP_ID_45)); }
    return this.__DomRootRenderer_52;
  }
  get _RootRenderer_53():any {
    if ((this.__RootRenderer_53 == null)) { (this.__RootRenderer_53 = import83._createConditionalRootRenderer(this._DomRootRenderer_52,this.parent.get(import83.NgProbeToken,(null as any)))); }
    return this.__RootRenderer_53;
  }
  get _DomSanitizer_54():import46.DomSanitizerImpl {
    if ((this.__DomSanitizer_54 == null)) { (this.__DomSanitizer_54 = new import46.DomSanitizerImpl()); }
    return this.__DomSanitizer_54;
  }
  get _Sanitizer_55():any {
    if ((this.__Sanitizer_55 == null)) { (this.__Sanitizer_55 = this._DomSanitizer_54); }
    return this.__Sanitizer_55;
  }
  get _ViewUtils_56():import47.ViewUtils {
    if ((this.__ViewUtils_56 == null)) { (this.__ViewUtils_56 = new import47.ViewUtils(this._RootRenderer_53,this._Sanitizer_55)); }
    return this.__ViewUtils_56;
  }
  get _IterableDiffers_57():any {
    if ((this.__IterableDiffers_57 == null)) { (this.__IterableDiffers_57 = import3._iterableDiffersFactory()); }
    return this.__IterableDiffers_57;
  }
  get _KeyValueDiffers_58():any {
    if ((this.__KeyValueDiffers_58 == null)) { (this.__KeyValueDiffers_58 = import3._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_58;
  }
  get _SharedStylesHost_59():any {
    if ((this.__SharedStylesHost_59 == null)) { (this.__SharedStylesHost_59 = this._DomSharedStylesHost_50); }
    return this.__SharedStylesHost_59;
  }
  get _Title_60():import48.Title {
    if ((this.__Title_60 == null)) { (this.__Title_60 = new import48.Title()); }
    return this.__Title_60;
  }
  get _RadioControlRegistry_61():import49.RadioControlRegistry {
    if ((this.__RadioControlRegistry_61 == null)) { (this.__RadioControlRegistry_61 = new import49.RadioControlRegistry()); }
    return this.__RadioControlRegistry_61;
  }
  get _BrowserXhr_62():import50.BrowserXhr {
    if ((this.__BrowserXhr_62 == null)) { (this.__BrowserXhr_62 = new import50.BrowserXhr()); }
    return this.__BrowserXhr_62;
  }
  get _ResponseOptions_63():import51.BaseResponseOptions {
    if ((this.__ResponseOptions_63 == null)) { (this.__ResponseOptions_63 = new import51.BaseResponseOptions()); }
    return this.__ResponseOptions_63;
  }
  get _XSRFStrategy_64():any {
    if ((this.__XSRFStrategy_64 == null)) { (this.__XSRFStrategy_64 = import7._createDefaultCookieXSRFStrategy()); }
    return this.__XSRFStrategy_64;
  }
  get _XHRBackend_65():import52.XHRBackend {
    if ((this.__XHRBackend_65 == null)) { (this.__XHRBackend_65 = new import52.XHRBackend(this._BrowserXhr_62,this._ResponseOptions_63,this._XSRFStrategy_64)); }
    return this.__XHRBackend_65;
  }
  get _RequestOptions_66():import53.BaseRequestOptions {
    if ((this.__RequestOptions_66 == null)) { (this.__RequestOptions_66 = new import53.BaseRequestOptions()); }
    return this.__RequestOptions_66;
  }
  get _Http_67():any {
    if ((this.__Http_67 == null)) { (this.__Http_67 = import7.httpFactory(this._XHRBackend_65,this._RequestOptions_66)); }
    return this.__Http_67;
  }
  get _MdLiveAnnouncer_68():import54.MdLiveAnnouncer {
    if ((this.__MdLiveAnnouncer_68 == null)) { (this.__MdLiveAnnouncer_68 = new import54.MdLiveAnnouncer(this.parent.get(import54.LIVE_ANNOUNCER_ELEMENT_TOKEN,(null as any)))); }
    return this.__MdLiveAnnouncer_68;
  }
  get _InteractivityChecker_69():import55.InteractivityChecker {
    if ((this.__InteractivityChecker_69 == null)) { (this.__InteractivityChecker_69 = new import55.InteractivityChecker()); }
    return this.__InteractivityChecker_69;
  }
  get _MdUniqueSelectionDispatcher_70():import56.MdUniqueSelectionDispatcher {
    if ((this.__MdUniqueSelectionDispatcher_70 == null)) { (this.__MdUniqueSelectionDispatcher_70 = new import56.MdUniqueSelectionDispatcher()); }
    return this.__MdUniqueSelectionDispatcher_70;
  }
  get _OverlayContainer_71():import57.OverlayContainer {
    if ((this.__OverlayContainer_71 == null)) { (this.__OverlayContainer_71 = new import57.OverlayContainer()); }
    return this.__OverlayContainer_71;
  }
  get _ViewportRuler_72():import58.ViewportRuler {
    if ((this.__ViewportRuler_72 == null)) { (this.__ViewportRuler_72 = new import58.ViewportRuler()); }
    return this.__ViewportRuler_72;
  }
  get _OverlayPositionBuilder_73():import59.OverlayPositionBuilder {
    if ((this.__OverlayPositionBuilder_73 == null)) { (this.__OverlayPositionBuilder_73 = new import59.OverlayPositionBuilder(this._ViewportRuler_72)); }
    return this.__OverlayPositionBuilder_73;
  }
  get _Overlay_74():import60.Overlay {
    if ((this.__Overlay_74 == null)) { (this.__Overlay_74 = new import60.Overlay(this._OverlayContainer_71,this,this._OverlayPositionBuilder_73,this._ApplicationRef_43,this)); }
    return this.__Overlay_74;
  }
  get _MdDialog_75():import26.MdDialog {
    if ((this.__MdDialog_75 == null)) { (this.__MdDialog_75 = new import26.MdDialog(this._Overlay_74,this)); }
    return this.__MdDialog_75;
  }
  get _MdIconRegistry_76():import61.MdIconRegistry {
    if ((this.__MdIconRegistry_76 == null)) { (this.__MdIconRegistry_76 = new import61.MdIconRegistry(this._Http_67)); }
    return this.__MdIconRegistry_76;
  }
  get _MdSnackBar_77():import32.MdSnackBar {
    if ((this.__MdSnackBar_77 == null)) { (this.__MdSnackBar_77 = new import32.MdSnackBar(this._Overlay_74,this._MdLiveAnnouncer_68)); }
    return this.__MdSnackBar_77;
  }
  get _ROUTER_CONFIGURATION_78():any {
    if ((this.__ROUTER_CONFIGURATION_78 == null)) { (this.__ROUTER_CONFIGURATION_78 = {}); }
    return this.__ROUTER_CONFIGURATION_78;
  }
  get _LocationStrategy_79():any {
    if ((this.__LocationStrategy_79 == null)) { (this.__LocationStrategy_79 = import36.provideLocationStrategy(this.parent.get(import84.PlatformLocation),this.parent.get(import85.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_78)); }
    return this.__LocationStrategy_79;
  }
  get _Location_80():import62.Location {
    if ((this.__Location_80 == null)) { (this.__Location_80 = new import62.Location(this._LocationStrategy_79)); }
    return this.__Location_80;
  }
  get _UrlSerializer_81():import63.DefaultUrlSerializer {
    if ((this.__UrlSerializer_81 == null)) { (this.__UrlSerializer_81 = new import63.DefaultUrlSerializer()); }
    return this.__UrlSerializer_81;
  }
  get _RouterOutletMap_82():import64.RouterOutletMap {
    if ((this.__RouterOutletMap_82 == null)) { (this.__RouterOutletMap_82 = new import64.RouterOutletMap()); }
    return this.__RouterOutletMap_82;
  }
  get _NgModuleFactoryLoader_83():import65.SystemJsNgModuleLoader {
    if ((this.__NgModuleFactoryLoader_83 == null)) { (this.__NgModuleFactoryLoader_83 = new import65.SystemJsNgModuleLoader(this._Compiler_44,this.parent.get(import65.SystemJsNgModuleLoaderConfig,(null as any)))); }
    return this.__NgModuleFactoryLoader_83;
  }
  get _ROUTES_84():any[] {
      if ((this.__ROUTES_84 == null)) { (this.__ROUTES_84 = [[
        {
          path: '',
          component: import86.AppComponent
        }
        ,
        {
          path: 'login',
          component: import87.LoginComponent
        }
        ,
        {
          path: 'dashboard',
          component: import88.DashboardComponent
        }
        ,
        {
          path: 'invite',
          component: import89.InviteComponent
        }
        ,
        {
          path: 'signup',
          component: import90.SignupComponent
        }
        ,
        {
          path: 'profile',
          component: import91.ProfileComponent
        }

      ]
    ]); }
    return this.__ROUTES_84;
  }
  get _Router_85():any {
    if ((this.__Router_85 == null)) { (this.__Router_85 = import36.setupRouter(this._ApplicationRef_43,this._UrlSerializer_81,this._RouterOutletMap_82,this._Location_80,this,this._NgModuleFactoryLoader_83,this._Compiler_44,this._ROUTES_84,this._ROUTER_CONFIGURATION_78,this.parent.get(import92.UrlHandlingStrategy,(null as any)))); }
    return this.__Router_85;
  }
  get _ActivatedRoute_86():any {
    if ((this.__ActivatedRoute_86 == null)) { (this.__ActivatedRoute_86 = import36.rootRoute(this._Router_85)); }
    return this.__ActivatedRoute_86;
  }
  get _PreloadAllModules_90():import66.PreloadAllModules {
    if ((this.__PreloadAllModules_90 == null)) { (this.__PreloadAllModules_90 = new import66.PreloadAllModules()); }
    return this.__PreloadAllModules_90;
  }
  get _ROUTER_INITIALIZER_91():any {
    if ((this.__ROUTER_INITIALIZER_91 == null)) { (this.__ROUTER_INITIALIZER_91 = import36.initialRouterNavigation(this._Router_85,this._ApplicationRef_43,this._RouterPreloader_89,this._ROUTER_CONFIGURATION_78)); }
    return this.__ROUTER_INITIALIZER_91;
  }
  get _APP_BOOTSTRAP_LISTENER_92():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_92 == null)) { (this.__APP_BOOTSTRAP_LISTENER_92 = [this._ROUTER_INITIALIZER_91]); }
    return this.__APP_BOOTSTRAP_LISTENER_92;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import3.ApplicationModule();
    this._BrowserModule_2 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._InternalFormsSharedModule_3 = new import5.InternalFormsSharedModule();
    this._FormsModule_4 = new import6.FormsModule();
    this._HttpModule_5 = new import7.HttpModule();
    this._MdRippleModule_6 = new import8.MdRippleModule();
    this._MdButtonModule_7 = new import9.MdButtonModule();
    this._MdCardModule_8 = new import10.MdCardModule();
    this._MdCheckboxModule_9 = new import11.MdCheckboxModule();
    this._MdLineModule_10 = new import12.MdLineModule();
    this._MdGridListModule_11 = new import13.MdGridListModule();
    this._MdInputModule_12 = new import14.MdInputModule();
    this._MdListModule_13 = new import15.MdListModule();
    this._MdProgressBarModule_14 = new import16.MdProgressBarModule();
    this._MdProgressCircleModule_15 = new import17.MdProgressCircleModule();
    this._MdSidenavModule_16 = new import18.MdSidenavModule();
    this._PortalModule_17 = new import19.PortalModule();
    this._MdTabsModule_18 = new import20.MdTabsModule();
    this._MdToolbarModule_19 = new import21.MdToolbarModule();
    this._RtlModule_20 = new import22.RtlModule();
    this._A11yModule_21 = new import23.A11yModule();
    this._MdButtonToggleModule_22 = new import24.MdButtonToggleModule();
    this._OverlayModule_23 = new import25.OverlayModule();
    this._MdDialogModule_24 = new import26.MdDialogModule();
    this._MdIconModule_25 = new import27.MdIconModule();
    this._MdMenuModule_26 = new import28.MdMenuModule();
    this._MdRadioModule_27 = new import29.MdRadioModule();
    this._MdSliderModule_28 = new import30.MdSliderModule();
    this._MdSlideToggleModule_29 = new import31.MdSlideToggleModule();
    this._MdSnackBarModule_30 = new import32.MdSnackBarModule();
    this._MdTooltipModule_31 = new import33.MdTooltipModule();
    this._StyleCompatibilityModule_32 = new import34.StyleCompatibilityModule();
    this._MaterialRootModule_33 = new import35.MaterialRootModule();
    this._ROUTER_FORROOT_GUARD_34 = import36.provideForRootGuard(this.parent.get(import93.Router,(null as any)));
    this._RouterModule_35 = new import36.RouterModule(this._ROUTER_FORROOT_GUARD_34);
    this._AppModule_36 = new import1.AppModule();
    this._ErrorHandler_39 = import4.errorHandler();
    this._ApplicationInitStatus_40 = new import38.ApplicationInitStatus(this.parent.get(import38.APP_INITIALIZER,(null as any)));
    this._Testability_41 = new import39.Testability(this.parent.get(import82.NgZone));
    this._ApplicationRef__42 = new import40.ApplicationRef_(this.parent.get(import82.NgZone),this.parent.get(import94.Console),this,this._ErrorHandler_39,this,this._ApplicationInitStatus_40,this.parent.get(import39.TestabilityRegistry,(null as any)),this._Testability_41);
    this._NoPreloading_87 = new import66.NoPreloading();
    this._PreloadingStrategy_88 = this._NoPreloading_87;
    this._RouterPreloader_89 = new import66.RouterPreloader(this._Router_85,this._NgModuleFactoryLoader_83,this._Compiler_44,this,this._PreloadingStrategy_88);
    return this._AppModule_36;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_2; }
    if ((token === import5.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_3; }
    if ((token === import6.FormsModule)) { return this._FormsModule_4; }
    if ((token === import7.HttpModule)) { return this._HttpModule_5; }
    if ((token === import8.MdRippleModule)) { return this._MdRippleModule_6; }
    if ((token === import9.MdButtonModule)) { return this._MdButtonModule_7; }
    if ((token === import10.MdCardModule)) { return this._MdCardModule_8; }
    if ((token === import11.MdCheckboxModule)) { return this._MdCheckboxModule_9; }
    if ((token === import12.MdLineModule)) { return this._MdLineModule_10; }
    if ((token === import13.MdGridListModule)) { return this._MdGridListModule_11; }
    if ((token === import14.MdInputModule)) { return this._MdInputModule_12; }
    if ((token === import15.MdListModule)) { return this._MdListModule_13; }
    if ((token === import16.MdProgressBarModule)) { return this._MdProgressBarModule_14; }
    if ((token === import17.MdProgressCircleModule)) { return this._MdProgressCircleModule_15; }
    if ((token === import18.MdSidenavModule)) { return this._MdSidenavModule_16; }
    if ((token === import19.PortalModule)) { return this._PortalModule_17; }
    if ((token === import20.MdTabsModule)) { return this._MdTabsModule_18; }
    if ((token === import21.MdToolbarModule)) { return this._MdToolbarModule_19; }
    if ((token === import22.RtlModule)) { return this._RtlModule_20; }
    if ((token === import23.A11yModule)) { return this._A11yModule_21; }
    if ((token === import24.MdButtonToggleModule)) { return this._MdButtonToggleModule_22; }
    if ((token === import25.OverlayModule)) { return this._OverlayModule_23; }
    if ((token === import26.MdDialogModule)) { return this._MdDialogModule_24; }
    if ((token === import27.MdIconModule)) { return this._MdIconModule_25; }
    if ((token === import28.MdMenuModule)) { return this._MdMenuModule_26; }
    if ((token === import29.MdRadioModule)) { return this._MdRadioModule_27; }
    if ((token === import30.MdSliderModule)) { return this._MdSliderModule_28; }
    if ((token === import31.MdSlideToggleModule)) { return this._MdSlideToggleModule_29; }
    if ((token === import32.MdSnackBarModule)) { return this._MdSnackBarModule_30; }
    if ((token === import33.MdTooltipModule)) { return this._MdTooltipModule_31; }
    if ((token === import34.StyleCompatibilityModule)) { return this._StyleCompatibilityModule_32; }
    if ((token === import35.MaterialRootModule)) { return this._MaterialRootModule_33; }
    if ((token === import36.ROUTER_FORROOT_GUARD)) { return this._ROUTER_FORROOT_GUARD_34; }
    if ((token === import36.RouterModule)) { return this._RouterModule_35; }
    if ((token === import1.AppModule)) { return this._AppModule_36; }
    if ((token === import95.LOCALE_ID)) { return this._LOCALE_ID_37; }
    if ((token === import37.NgLocalization)) { return this._NgLocalization_38; }
    if ((token === import96.ErrorHandler)) { return this._ErrorHandler_39; }
    if ((token === import38.ApplicationInitStatus)) { return this._ApplicationInitStatus_40; }
    if ((token === import39.Testability)) { return this._Testability_41; }
    if ((token === import40.ApplicationRef_)) { return this._ApplicationRef__42; }
    if ((token === import40.ApplicationRef)) { return this._ApplicationRef_43; }
    if ((token === import41.Compiler)) { return this._Compiler_44; }
    if ((token === import78.APP_ID)) { return this._APP_ID_45; }
    if ((token === import97.DOCUMENT)) { return this._DOCUMENT_46; }
    if ((token === import81.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_47; }
    if ((token === import43.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_48; }
    if ((token === import43.EventManager)) { return this._EventManager_49; }
    if ((token === import44.DomSharedStylesHost)) { return this._DomSharedStylesHost_50; }
    if ((token === import98.AnimationDriver)) { return this._AnimationDriver_51; }
    if ((token === import45.DomRootRenderer)) { return this._DomRootRenderer_52; }
    if ((token === import99.RootRenderer)) { return this._RootRenderer_53; }
    if ((token === import46.DomSanitizer)) { return this._DomSanitizer_54; }
    if ((token === import100.Sanitizer)) { return this._Sanitizer_55; }
    if ((token === import47.ViewUtils)) { return this._ViewUtils_56; }
    if ((token === import101.IterableDiffers)) { return this._IterableDiffers_57; }
    if ((token === import102.KeyValueDiffers)) { return this._KeyValueDiffers_58; }
    if ((token === import44.SharedStylesHost)) { return this._SharedStylesHost_59; }
    if ((token === import48.Title)) { return this._Title_60; }
    if ((token === import49.RadioControlRegistry)) { return this._RadioControlRegistry_61; }
    if ((token === import50.BrowserXhr)) { return this._BrowserXhr_62; }
    if ((token === import51.ResponseOptions)) { return this._ResponseOptions_63; }
    if ((token === import103.XSRFStrategy)) { return this._XSRFStrategy_64; }
    if ((token === import52.XHRBackend)) { return this._XHRBackend_65; }
    if ((token === import53.RequestOptions)) { return this._RequestOptions_66; }
    if ((token === import104.Http)) { return this._Http_67; }
    if ((token === import54.MdLiveAnnouncer)) { return this._MdLiveAnnouncer_68; }
    if ((token === import55.InteractivityChecker)) { return this._InteractivityChecker_69; }
    if ((token === import56.MdUniqueSelectionDispatcher)) { return this._MdUniqueSelectionDispatcher_70; }
    if ((token === import57.OverlayContainer)) { return this._OverlayContainer_71; }
    if ((token === import58.ViewportRuler)) { return this._ViewportRuler_72; }
    if ((token === import59.OverlayPositionBuilder)) { return this._OverlayPositionBuilder_73; }
    if ((token === import60.Overlay)) { return this._Overlay_74; }
    if ((token === import26.MdDialog)) { return this._MdDialog_75; }
    if ((token === import61.MdIconRegistry)) { return this._MdIconRegistry_76; }
    if ((token === import32.MdSnackBar)) { return this._MdSnackBar_77; }
    if ((token === import36.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_78; }
    if ((token === import85.LocationStrategy)) { return this._LocationStrategy_79; }
    if ((token === import62.Location)) { return this._Location_80; }
    if ((token === import63.UrlSerializer)) { return this._UrlSerializer_81; }
    if ((token === import64.RouterOutletMap)) { return this._RouterOutletMap_82; }
    if ((token === import105.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_83; }
    if ((token === import106.ROUTES)) { return this._ROUTES_84; }
    if ((token === import93.Router)) { return this._Router_85; }
    if ((token === import107.ActivatedRoute)) { return this._ActivatedRoute_86; }
    if ((token === import66.NoPreloading)) { return this._NoPreloading_87; }
    if ((token === import66.PreloadingStrategy)) { return this._PreloadingStrategy_88; }
    if ((token === import66.RouterPreloader)) { return this._RouterPreloader_89; }
    if ((token === import66.PreloadAllModules)) { return this._PreloadAllModules_90; }
    if ((token === import36.ROUTER_INITIALIZER)) { return this._ROUTER_INITIALIZER_91; }
    if ((token === import78.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_92; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__42.ngOnDestroy();
    this._RouterPreloader_89.ngOnDestroy();
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory(AppModuleInjector,import1.AppModule);