apiVersion: v1
kind: PersistentVolume
metadata:
  name: stage001
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: stage001
    fsType: ext4