apiVersion: v1
kind: ReplicationController
metadata:
  generateName: frontend-master-
  labels:
    name: frontend
    version: v0.0.0
spec:
  replicas: 1
  selector:
    name: frontend
    version: v0.0.0
  template:
    metadata:
      labels:
        name: frontend
        version: v0.0.0
    spec:
      containers:
        - name: frontend
          image: us.gcr.io/icanhelpyouwiththat-149304/frontend:latest
          env:
          - name: WEB_ENV
            value: production
          command: ["/bin/bash","-c", "nginx;"]
          ports:
            - containerPort: 3002
              name: http
