apiVersion: v1
kind: ReplicationController
metadata:
  name: letsencrypt
  namespace: default
spec:
  replicas: 1
  selector:
    app: letsencrypt
  template:
    metadata:
      name: letsencrypt
      labels:
        app: letsencrypt
    spec:
      containers:
      - name: letsencrypt
        image: us.gcr.io/icanhelpyouwiththat-149304/kubernetes-letsencrypt:latest
        imagePullPolicy: Always
        env:
          - name: tos
            value: "true"
          - name: country
            value: US
          - name: state
            value: Portsmouth
          - name: town
            value: Portsmouth
          - name: organization
            value: ICHUWT
          - name: email
            value: jesse.bowden@me.com
          - name: secretName
            value: tls
          - name: acmeServer
            value: https://acme-staging.api.letsencrypt.org/directory
          - name: namespace
            value: default
