/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../app/components/dashboard/dashboard.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/debug_context';
import * as import3 from '../../../../app/services/profile.service';
import * as import4 from '@angular/core/src/render/api';
import * as import5 from '@angular/core/src/linker/view_utils';
import * as import6 from '@angular/core/src/metadata/view';
import * as import7 from '@angular/core/src/linker/view_type';
import * as import8 from '@angular/core/src/change_detection/change_detection';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from '@angular/http/src/http';
import * as import11 from '@angular/router/src/router';
import * as import12 from './dashboard.component.css';
import * as import13 from '@angular/material/card/card';
import * as import14 from '@angular/material/core/compatibility/style-compatibility';
import * as import15 from '@angular/core/src/linker/template_ref';
import * as import16 from '@angular/common/src/directives/ng_if';
import * as import17 from '@angular/material/button/button';
import * as import18 from '@angular/router/src/directives/router_link';
import * as import19 from '../../../node_modules/@angular/material/card/card.ngfactory';
import * as import20 from '../../../node_modules/@angular/material/core/compatibility/style-compatibility.ngfactory';
import * as import21 from '@angular/core/src/linker/view_container';
import * as import22 from '../../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import23 from '../../../node_modules/@angular/material/button/button.ngfactory';
import * as import24 from '../../../node_modules/@angular/router/src/directives/router_link.ngfactory';
import * as import25 from '@angular/core/src/linker/element_ref';
import * as import26 from '@angular/router/src/router_state';
import * as import27 from '@angular/common/src/location/location_strategy';
export class Wrapper_DashboardComponent {
  /*private*/ _eventHandler:Function;
  context:import0.DashboardComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any) {
    this._changed = false;
    this.context = new import0.DashboardComponent(p0,p1);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
  const nodeDebugInfos_DashboardComponent_Host0:import2.StaticNodeDebugInfo[] = [new import2.StaticNodeDebugInfo([
    import3.ProfileService,
    import0.DashboardComponent
  ]
,import0.DashboardComponent,{})];
var renderType_DashboardComponent_Host:import4.RenderComponentType = import5.createRenderComponentType('',0,import6.ViewEncapsulation.None,([] as any[]),{});
class View_DashboardComponent_Host0 extends import1.DebugAppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.DashboardComponent>;
  _ProfileService_0_3:import3.ProfileService;
  _DashboardComponent_0_4:Wrapper_DashboardComponent;
  constructor(viewUtils:import5.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_DashboardComponent_Host0,renderType_DashboardComponent_Host,import7.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_DashboardComponent_Host0);
  }
  createInternal(rootSelector:string):import9.ComponentRef<any> {
    this._el_0 = import5.selectOrCreateRenderHostElement(this.renderer,'ng-component',import5.EMPTY_INLINE_ARRAY,rootSelector,this.debug(0,0,0));
    this.compView_0 = new View_DashboardComponent0(this.viewUtils,this,0,this._el_0);
    this._ProfileService_0_3 = new import3.ProfileService(this.injectorGet(import10.Http,this.parentIndex));
    this._DashboardComponent_0_4 = new Wrapper_DashboardComponent(this._ProfileService_0_3,this.injectorGet(import11.Router,this.parentIndex));
    this.compView_0.create(this._DashboardComponent_0_4.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import9.ComponentRef_<any>(0,this,this._el_0,this._DashboardComponent_0_4.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.ProfileService) && (0 === requestNodeIndex))) { return this._ProfileService_0_3; }
    if (((token === import0.DashboardComponent) && (0 === requestNodeIndex))) { return this._DashboardComponent_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.debug(0,0,0);
    this._DashboardComponent_0_4.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const DashboardComponentNgFactory:import9.ComponentFactory<import0.DashboardComponent> = new import9.ComponentFactory<import0.DashboardComponent>('ng-component',View_DashboardComponent_Host0,import0.DashboardComponent);
const styles_DashboardComponent:any[] = [import12.styles];
const nodeDebugInfos_DashboardComponent0:import2.StaticNodeDebugInfo[] = [
  new import2.StaticNodeDebugInfo([
    import13.MdCard,
    import14.StyleCompatibility
  ]
  ,import13.MdCard,{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([
    import13.MdCardContent,
    import14.StyleCompatibility
  ]
  ,(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([
    import15.TemplateRef,
    import16.NgIf
  ]
  ,(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([
    import13.MdCardActions,
    import14.StyleCompatibility
  ]
  ,(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([
    import17.MdButton,
    import18.RouterLink
  ]
  ,import17.MdButton,{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([import17.MdButton],import17.MdButton,{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{})
]
;
var renderType_DashboardComponent:import4.RenderComponentType = import5.createRenderComponentType('/Users/jessebowden/ichuwt/frontend/src/app/components/dashboard/dashboard.component.html',0,import6.ViewEncapsulation.None,styles_DashboardComponent,{});
export class View_DashboardComponent0 extends import1.DebugAppView<import0.DashboardComponent> {
  _el_0:any;
  compView_0:import1.AppView<import13.MdCard>;
  _MdCard_0_3:import19.Wrapper_MdCard;
  _StyleCompatibility_0_4:import20.Wrapper_StyleCompatibility;
  _text_1:any;
  _el_2:any;
  _MdCardContent_2_3:import19.Wrapper_MdCardContent;
  _StyleCompatibility_2_4:import20.Wrapper_StyleCompatibility;
  _text_3:any;
  _anchor_4:any;
  /*private*/ _vc_4:import21.ViewContainer;
  _TemplateRef_4_5:any;
  _NgIf_4_6:import22.Wrapper_NgIf;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _MdCardActions_13_3:import19.Wrapper_MdCardActions;
  _StyleCompatibility_13_4:import20.Wrapper_StyleCompatibility;
  _text_14:any;
  _el_15:any;
  compView_15:import1.AppView<import17.MdButton>;
  _MdButton_15_3:import23.Wrapper_MdButton;
  _RouterLink_15_4:import24.Wrapper_RouterLink;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  compView_18:import1.AppView<import17.MdButton>;
  _MdButton_18_3:import23.Wrapper_MdButton;
  _text_19:any;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  constructor(viewUtils:import5.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_DashboardComponent0,renderType_DashboardComponent,import7.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_DashboardComponent0);
  }
  createInternal(rootSelector:string):import9.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import5.createRenderElement(this.renderer,parentRenderNode,'md-card',new import5.InlineArray4(4,'class','help_you','id','help_you'),this.debug(0,0,0));
    this.compView_0 = new import19.View_MdCard0(this.viewUtils,this,0,this._el_0);
    this._MdCard_0_3 = new import19.Wrapper_MdCard();
    this._StyleCompatibility_0_4 = new import20.Wrapper_StyleCompatibility(this.renderer,new import25.ElementRef(this._el_0));
    this._text_1 = this.renderer.createText((null as any),'\n  ',this.debug(1,0,40));
    this._el_2 = import5.createRenderElement(this.renderer,(null as any),'md-card-content',import5.EMPTY_INLINE_ARRAY,this.debug(2,1,2));
    this._MdCardContent_2_3 = new import19.Wrapper_MdCardContent();
    this._StyleCompatibility_2_4 = new import20.Wrapper_StyleCompatibility(this.renderer,new import25.ElementRef(this._el_2));
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',this.debug(3,1,19));
    this._anchor_4 = this.renderer.createTemplateAnchor(this._el_2,this.debug(4,2,4));
    this._vc_4 = new import21.ViewContainer(4,2,this,this._anchor_4);
    this._TemplateRef_4_5 = new import15.TemplateRef_(this,4,this._anchor_4);
    this._NgIf_4_6 = new import22.Wrapper_NgIf(this._vc_4.vcRef,this._TemplateRef_4_5);
    this._text_5 = this.renderer.createText(this._el_2,'\n\n    My Tasks\n    ',this.debug(5,2,56));
    this._el_6 = import5.createRenderElement(this.renderer,this._el_2,'div',import5.EMPTY_INLINE_ARRAY,this.debug(6,5,4));
    this._text_7 = this.renderer.createText(this._el_6,'\n      Find your first task\n      ',this.debug(7,5,9));
    this._el_8 = import5.createRenderElement(this.renderer,this._el_6,'a',new import5.InlineArray2(2,'href','#'),this.debug(8,7,6));
    this._text_9 = this.renderer.createText(this._el_8,'Search Tasks',this.debug(9,7,18));
    this._text_10 = this.renderer.createText(this._el_6,'\n    ',this.debug(10,7,34));
    this._text_11 = this.renderer.createText(this._el_2,'\n  ',this.debug(11,8,10));
    this._text_12 = this.renderer.createText((null as any),'\n  ',this.debug(12,9,20));
    this._el_13 = import5.createRenderElement(this.renderer,(null as any),'md-card-actions',import5.EMPTY_INLINE_ARRAY,this.debug(13,10,2));
    this._MdCardActions_13_3 = new import19.Wrapper_MdCardActions();
    this._StyleCompatibility_13_4 = new import20.Wrapper_StyleCompatibility(this.renderer,new import25.ElementRef(this._el_13));
    this._text_14 = this.renderer.createText(this._el_13,'\n    ',this.debug(14,10,19));
    this._el_15 = import5.createRenderElement(this.renderer,this._el_13,'button',new import5.InlineArray4(4,'md-button','','routerLink','/invite'),this.debug(15,11,4));
    this.compView_15 = new import23.View_MdButton0(this.viewUtils,this,15,this._el_15);
    this._MdButton_15_3 = new import23.Wrapper_MdButton(new import25.ElementRef(this._el_15),this.renderer);
    this._RouterLink_15_4 = new import24.Wrapper_RouterLink(this.parentView.injectorGet(import11.Router,this.parentIndex),this.parentView.injectorGet(import26.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import27.LocationStrategy,this.parentIndex));
    this._text_16 = this.renderer.createText((null as any),'Invite friends',this.debug(16,11,43));
    this.compView_15.create(this._MdButton_15_3.context);
    this._text_17 = this.renderer.createText(this._el_13,'\n    ',this.debug(17,11,66));
    this._el_18 = import5.createRenderElement(this.renderer,this._el_13,'button',new import5.InlineArray2(2,'md-button',''),this.debug(18,12,4));
    this.compView_18 = new import23.View_MdButton0(this.viewUtils,this,18,this._el_18);
    this._MdButton_18_3 = new import23.Wrapper_MdButton(new import25.ElementRef(this._el_18),this.renderer);
    this._text_19 = this.renderer.createText((null as any),'Search tasks',this.debug(19,12,22));
    this.compView_18.create(this._MdButton_18_3.context);
    this._text_20 = this.renderer.createText(this._el_13,'\n  ',this.debug(20,12,43));
    this._text_21 = this.renderer.createText((null as any),'\n',this.debug(21,13,20));
    this.compView_0.create(this._MdCard_0_3.context);
    this._text_22 = this.renderer.createText(parentRenderNode,'\n',this.debug(22,14,10));
    var disposable_0:Function = import5.subscribeToRenderElement(this,this._el_15,new import5.InlineArray8(8,'mousedown',(null as any),'focus',(null as any),'blur',(null as any),'click',(null as any)),this.eventHandler(this.handleEvent_15));
    var disposable_1:Function = import5.subscribeToRenderElement(this,this._el_18,new import5.InlineArray8(6,'mousedown',(null as any),'focus',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_18));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._anchor_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._text_21,
      this._text_22
    ]
    ),[
      disposable_0,
      disposable_1
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import15.TemplateRef) && (4 === requestNodeIndex))) { return this._TemplateRef_4_5; }
    if (((token === import16.NgIf) && (4 === requestNodeIndex))) { return this._NgIf_4_6.context; }
    if (((token === import13.MdCardContent) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._MdCardContent_2_3.context; }
    if (((token === import14.StyleCompatibility) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._StyleCompatibility_2_4.context; }
    if (((token === import17.MdButton) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._MdButton_15_3.context; }
    if (((token === import18.RouterLink) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._RouterLink_15_4.context; }
    if (((token === import17.MdButton) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._MdButton_18_3.context; }
    if (((token === import13.MdCardActions) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._MdCardActions_13_3.context; }
    if (((token === import14.StyleCompatibility) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._StyleCompatibility_13_4.context; }
    if (((token === import13.MdCard) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._MdCard_0_3.context; }
    if (((token === import14.StyleCompatibility) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._StyleCompatibility_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.debug(0,0,0);
    if (this._MdCard_0_3.ngDoCheck(this,this._el_0,throwOnChange)) { this.compView_0.markAsCheckOnce(); }
    this._StyleCompatibility_0_4.ngDoCheck(this,this._el_0,throwOnChange);
    this.debug(2,1,2);
    this._MdCardContent_2_3.ngDoCheck(this,this._el_2,throwOnChange);
    this._StyleCompatibility_2_4.ngDoCheck(this,this._el_2,throwOnChange);
    this.debug(4,2,8);
    const currVal_4_0_0:any = this.context.profile;
    this._NgIf_4_6.check_ngIf(currVal_4_0_0,throwOnChange,false);
    this._NgIf_4_6.ngDoCheck(this,this._anchor_4,throwOnChange);
    this.debug(13,10,2);
    this._MdCardActions_13_3.ngDoCheck(this,this._el_13,throwOnChange);
    this._StyleCompatibility_13_4.ngDoCheck(this,this._el_13,throwOnChange);
    this.debug(15,11,4);
    if (this._MdButton_15_3.ngDoCheck(this,this._el_15,throwOnChange)) { this.compView_15.markAsCheckOnce(); }
    this.debug(15,11,12);
    const currVal_15_1_0:any = '/invite';
    this._RouterLink_15_4.check_routerLink(currVal_15_1_0,throwOnChange,false);
    this._RouterLink_15_4.ngDoCheck(this,this._el_15,throwOnChange);
    this.debug(18,12,4);
    if (this._MdButton_18_3.ngDoCheck(this,this._el_18,throwOnChange)) { this.compView_18.markAsCheckOnce(); }
    this._vc_4.detectChangesInNestedViews(throwOnChange);
    this._MdButton_15_3.checkHost(this,this.compView_15,this._el_15,throwOnChange);
    this._MdButton_18_3.checkHost(this,this.compView_18,this._el_18,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
    this.compView_15.detectChanges(throwOnChange);
    this.compView_18.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this._vc_4.destroyNestedViews();
    this.compView_0.destroy();
    this.compView_15.destroy();
    this.compView_18.destroy();
    this.debug(4,2,4);
    this.debug(2,1,2);
    this.debug(15,11,4);
    this.debug(18,12,4);
    this.debug(13,10,2);
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 0) && (ngContentIndex == 0))) {
      cb(this._text_1,ctx);
      cb(this._el_2,ctx);
      cb(this._text_12,ctx);
      cb(this._el_13,ctx);
      cb(this._text_21,ctx);
    }
    if (((nodeIndex == 15) && (ngContentIndex == 0))) { cb(this._text_16,ctx); }
    if (((nodeIndex == 18) && (ngContentIndex == 0))) { cb(this._text_19,ctx); }
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 4)) { return new View_DashboardComponent1(this.viewUtils,this,4,this._anchor_4,this._vc_4); }
    return (null as any);
  }
  handleEvent_15(eventName:string,$event:any):boolean {
    this.debug(15,11,4);
    this.compView_15.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdButton_15_3.handleEvent(eventName,$event) && result);
    result = (this._RouterLink_15_4.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_18(eventName:string,$event:any):boolean {
    this.debug(18,12,4);
    this.compView_18.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdButton_18_3.handleEvent(eventName,$event) && result);
    return result;
  }
}
const nodeDebugInfos_DashboardComponent1:import2.StaticNodeDebugInfo[] = [
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{})
]
;
class View_DashboardComponent1 extends import1.DebugAppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import5.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import21.ViewContainer) {
    super(View_DashboardComponent1,renderType_DashboardComponent,import7.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_DashboardComponent1,declaredViewContainer);
    this._expr_2 = import8.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import9.ComponentRef<any> {
    this._el_0 = import5.createRenderElement(this.renderer,(null as any),'h2',import5.EMPTY_INLINE_ARRAY,this.debug(0,2,4));
    this._text_1 = this.renderer.createText(this._el_0,'',this.debug(1,2,24));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.debug(1,2,24);
    const currVal_2:any = import5.inlineInterpolate(1,'Welcome, ',this.parentView.context.profile.name,'');
    if (import5.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_1,currVal_2);
      this._expr_2 = currVal_2;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}