/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../app/components/login/login.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/debug_context';
import * as import3 from '../../../../app/services/profile.service';
import * as import4 from '@angular/core/src/render/api';
import * as import5 from '@angular/core/src/linker/view_utils';
import * as import6 from '@angular/core/src/metadata/view';
import * as import7 from '@angular/core/src/linker/view_type';
import * as import8 from '@angular/core/src/change_detection/change_detection';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from '@angular/http/src/http';
import * as import11 from '@angular/router/src/router';
import * as import12 from './login.component.css';
import * as import13 from '@angular/material/card/card';
import * as import14 from '@angular/material/core/compatibility/style-compatibility';
import * as import15 from '@angular/forms/src/directives/ng_form';
import * as import16 from '@angular/forms/src/directives/control_container';
import * as import17 from '@angular/forms/src/directives/ng_control_status';
import * as import18 from '@angular/material/input/input';
import * as import19 from '@angular/forms/src/directives/control_value_accessor';
import * as import20 from '@angular/forms/src/directives/ng_model';
import * as import21 from '@angular/forms/src/directives/ng_control';
import * as import22 from '@angular/material/button/button';
import * as import23 from '@angular/router/src/directives/router_link';
import * as import24 from '@angular/router/src/directives/router_link_active';
import * as import25 from '../../../node_modules/@angular/material/card/card.ngfactory';
import * as import26 from '../../../node_modules/@angular/material/core/compatibility/style-compatibility.ngfactory';
import * as import27 from '../../../node_modules/@angular/forms/src/directives/ng_form.ngfactory';
import * as import28 from '../../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import29 from '../../../node_modules/@angular/material/input/input.ngfactory';
import * as import30 from '../../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import31 from '@angular/core/src/linker/query_list';
import * as import32 from '../../../node_modules/@angular/material/button/button.ngfactory';
import * as import33 from '../../../node_modules/@angular/router/src/directives/router_link.ngfactory';
import * as import34 from '../../../node_modules/@angular/router/src/directives/router_link_active.ngfactory';
import * as import35 from '@angular/core/src/linker/element_ref';
import * as import36 from '@angular/router/src/router_state';
import * as import37 from '@angular/common/src/location/location_strategy';
export class Wrapper_LoginComponent {
  /*private*/ _eventHandler:Function;
  context:import0.LoginComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any) {
    this._changed = false;
    this.context = new import0.LoginComponent(p0,p1);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
  const nodeDebugInfos_LoginComponent_Host0:import2.StaticNodeDebugInfo[] = [new import2.StaticNodeDebugInfo([
    import3.ProfileService,
    import0.LoginComponent
  ]
,import0.LoginComponent,{})];
var renderType_LoginComponent_Host:import4.RenderComponentType = import5.createRenderComponentType('',0,import6.ViewEncapsulation.None,([] as any[]),{});
class View_LoginComponent_Host0 extends import1.DebugAppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.LoginComponent>;
  _ProfileService_0_3:import3.ProfileService;
  _LoginComponent_0_4:Wrapper_LoginComponent;
  constructor(viewUtils:import5.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_LoginComponent_Host0,renderType_LoginComponent_Host,import7.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_LoginComponent_Host0);
  }
  createInternal(rootSelector:string):import9.ComponentRef<any> {
    this._el_0 = import5.selectOrCreateRenderHostElement(this.renderer,'ng-component',import5.EMPTY_INLINE_ARRAY,rootSelector,this.debug(0,0,0));
    this.compView_0 = new View_LoginComponent0(this.viewUtils,this,0,this._el_0);
    this._ProfileService_0_3 = new import3.ProfileService(this.injectorGet(import10.Http,this.parentIndex));
    this._LoginComponent_0_4 = new Wrapper_LoginComponent(this._ProfileService_0_3,this.injectorGet(import11.Router,this.parentIndex));
    this.compView_0.create(this._LoginComponent_0_4.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import9.ComponentRef_<any>(0,this,this._el_0,this._LoginComponent_0_4.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.ProfileService) && (0 === requestNodeIndex))) { return this._ProfileService_0_3; }
    if (((token === import0.LoginComponent) && (0 === requestNodeIndex))) { return this._LoginComponent_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.debug(0,0,0);
    this._LoginComponent_0_4.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const LoginComponentNgFactory:import9.ComponentFactory<import0.LoginComponent> = new import9.ComponentFactory<import0.LoginComponent>('ng-component',View_LoginComponent_Host0,import0.LoginComponent);
const styles_LoginComponent:any[] = [import12.styles];
const nodeDebugInfos_LoginComponent0:import2.StaticNodeDebugInfo[] = [
  new import2.StaticNodeDebugInfo([
    import13.MdCard,
    import14.StyleCompatibility
  ]
  ,import13.MdCard,{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([
    import13.MdCardContent,
    import14.StyleCompatibility
  ]
  ,(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([
    import15.NgForm,
    import16.ControlContainer,
    import17.NgControlStatusGroup
  ]
  ,(null as any),{loginForm: import15.NgForm}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([
    import18.MdInput,
    import19.NG_VALUE_ACCESSOR,
    import20.NgModel,
    import21.NgControl,
    import17.NgControlStatus,
    import14.StyleCompatibility
  ]
  ,import18.MdInput,{username: import20.NgModel}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([
    import18.MdInput,
    import19.NG_VALUE_ACCESSOR,
    import20.NgModel,
    import21.NgControl,
    import17.NgControlStatus,
    import14.StyleCompatibility
  ]
  ,import18.MdInput,{password: import20.NgModel}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([import22.MdButton],import22.MdButton,{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([
    import23.RouterLinkWithHref,
    import24.RouterLinkActive
  ]
  ,(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{})
]
;
var renderType_LoginComponent:import4.RenderComponentType = import5.createRenderComponentType('/Users/jessebowden/ichuwt/frontend/src/app/components/login/login.component.html',0,import6.ViewEncapsulation.None,styles_LoginComponent,{});
export class View_LoginComponent0 extends import1.DebugAppView<import0.LoginComponent> {
  _el_0:any;
  compView_0:import1.AppView<import13.MdCard>;
  _MdCard_0_3:import25.Wrapper_MdCard;
  _StyleCompatibility_0_4:import26.Wrapper_StyleCompatibility;
  _text_1:any;
  _el_2:any;
  _MdCardContent_2_3:import25.Wrapper_MdCardContent;
  _StyleCompatibility_2_4:import26.Wrapper_StyleCompatibility;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _NgForm_6_3:import27.Wrapper_NgForm;
  _ControlContainer_6_4:any;
  _NgControlStatusGroup_6_5:import28.Wrapper_NgControlStatusGroup;
  _text_7:any;
  _el_8:any;
  compView_8:import1.AppView<import18.MdInput>;
  _MdInput_8_3:import29.Wrapper_MdInput;
  _NG_VALUE_ACCESSOR_8_4:any[];
  _NgModel_8_5:import30.Wrapper_NgModel;
  _NgControl_8_6:any;
  _NgControlStatus_8_7:import28.Wrapper_NgControlStatus;
  _StyleCompatibility_8_8:import26.Wrapper_StyleCompatibility;
  _query_MdPlaceholder_8_0:import31.QueryList<any>;
  _query_MdHint_8_1:import31.QueryList<any>;
  _text_9:any;
  _el_10:any;
  compView_10:import1.AppView<import18.MdInput>;
  _MdInput_10_3:import29.Wrapper_MdInput;
  _NG_VALUE_ACCESSOR_10_4:any[];
  _NgModel_10_5:import30.Wrapper_NgModel;
  _NgControl_10_6:any;
  _NgControlStatus_10_7:import28.Wrapper_NgControlStatus;
  _StyleCompatibility_10_8:import26.Wrapper_StyleCompatibility;
  _query_MdPlaceholder_10_0:import31.QueryList<any>;
  _query_MdHint_10_1:import31.QueryList<any>;
  _text_11:any;
  _el_12:any;
  compView_12:import1.AppView<import22.MdButton>;
  _MdButton_12_3:import32.Wrapper_MdButton;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _el_20:any;
  _RouterLinkWithHref_20_3:import33.Wrapper_RouterLinkWithHref;
  _RouterLinkActive_20_4:import34.Wrapper_RouterLinkActive;
  _query_RouterLink_20_0:import31.QueryList<any>;
  _query_RouterLinkWithHref_20_1:import31.QueryList<any>;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  _text_24:any;
  _text_25:any;
  constructor(viewUtils:import5.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_LoginComponent0,renderType_LoginComponent,import7.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_LoginComponent0);
  }
  createInternal(rootSelector:string):import9.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import5.createRenderElement(this.renderer,parentRenderNode,'md-card',new import5.InlineArray4(4,'class','help_you','id','help_you'),this.debug(0,0,0));
    this.compView_0 = new import25.View_MdCard0(this.viewUtils,this,0,this._el_0);
    this._MdCard_0_3 = new import25.Wrapper_MdCard();
    this._StyleCompatibility_0_4 = new import26.Wrapper_StyleCompatibility(this.renderer,new import35.ElementRef(this._el_0));
    this._text_1 = this.renderer.createText((null as any),'\n  ',this.debug(1,0,40));
    this._el_2 = import5.createRenderElement(this.renderer,(null as any),'md-card-content',import5.EMPTY_INLINE_ARRAY,this.debug(2,1,2));
    this._MdCardContent_2_3 = new import25.Wrapper_MdCardContent();
    this._StyleCompatibility_2_4 = new import26.Wrapper_StyleCompatibility(this.renderer,new import35.ElementRef(this._el_2));
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',this.debug(3,1,19));
    this._el_4 = import5.createRenderElement(this.renderer,this._el_2,'img',new import5.InlineArray8(6,'class','content','md-card-image','','src','https://scontent.fbed1-2.fna.fbcdn.net/v/t1.0-9/15027882_10101666597237585_7556774340470305079_n.jpg?oh=635948e21d52a9aacc0ab9cc53a4e1ad&oe=58D120BD'),this.debug(4,2,4));
    this._text_5 = this.renderer.createText(this._el_2,'\n    ',this.debug(5,2,195));
    this._el_6 = import5.createRenderElement(this.renderer,this._el_2,'form',import5.EMPTY_INLINE_ARRAY,this.debug(6,3,4));
    this._NgForm_6_3 = new import27.Wrapper_NgForm((null as any),(null as any));
    this._ControlContainer_6_4 = this._NgForm_6_3.context;
    this._NgControlStatusGroup_6_5 = new import28.Wrapper_NgControlStatusGroup(this._ControlContainer_6_4);
    this._text_7 = this.renderer.createText(this._el_6,'\n      ',this.debug(7,3,51));
    this._el_8 = import5.createRenderElement(this.renderer,this._el_6,'md-input',new import5.InlineArray16(10,'align','start','class','login_input','id','email_input','name','username','placeholder','E-Mail'),this.debug(8,4,6));
    this.compView_8 = new import29.View_MdInput0(this.viewUtils,this,8,this._el_8);
    this._MdInput_8_3 = new import29.Wrapper_MdInput(new import35.ElementRef(this._el_8));
    this._NG_VALUE_ACCESSOR_8_4 = [this._MdInput_8_3.context];
    this._NgModel_8_5 = new import30.Wrapper_NgModel(this._ControlContainer_6_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_8_4);
    this._NgControl_8_6 = this._NgModel_8_5.context;
    this._NgControlStatus_8_7 = new import28.Wrapper_NgControlStatus(this._NgControl_8_6);
    this._StyleCompatibility_8_8 = new import26.Wrapper_StyleCompatibility(this.renderer,new import35.ElementRef(this._el_8));
    this._query_MdPlaceholder_8_0 = new import31.QueryList<any>();
    this._query_MdHint_8_1 = new import31.QueryList<any>();
    this._query_MdPlaceholder_8_0.reset(([] as any[]));
    this._MdInput_8_3.context._placeholderChild = this._query_MdPlaceholder_8_0.first;
    this.compView_8.create(this._MdInput_8_3.context);
    this._text_9 = this.renderer.createText(this._el_6,'\n      ',this.debug(9,4,168));
    this._el_10 = import5.createRenderElement(this.renderer,this._el_6,'md-input',new import5.InlineArray16(12,'align','start','class','login_input','id','password_input','name','password','placeholder','Password','type','password'),this.debug(10,5,6));
    this.compView_10 = new import29.View_MdInput0(this.viewUtils,this,10,this._el_10);
    this._MdInput_10_3 = new import29.Wrapper_MdInput(new import35.ElementRef(this._el_10));
    this._NG_VALUE_ACCESSOR_10_4 = [this._MdInput_10_3.context];
    this._NgModel_10_5 = new import30.Wrapper_NgModel(this._ControlContainer_6_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_10_4);
    this._NgControl_10_6 = this._NgModel_10_5.context;
    this._NgControlStatus_10_7 = new import28.Wrapper_NgControlStatus(this._NgControl_10_6);
    this._StyleCompatibility_10_8 = new import26.Wrapper_StyleCompatibility(this.renderer,new import35.ElementRef(this._el_10));
    this._query_MdPlaceholder_10_0 = new import31.QueryList<any>();
    this._query_MdHint_10_1 = new import31.QueryList<any>();
    this._query_MdPlaceholder_10_0.reset(([] as any[]));
    this._MdInput_10_3.context._placeholderChild = this._query_MdPlaceholder_10_0.first;
    this.compView_10.create(this._MdInput_10_3.context);
    this._text_11 = this.renderer.createText(this._el_6,'\n      ',this.debug(11,5,191));
    this._el_12 = import5.createRenderElement(this.renderer,this._el_6,'button',new import5.InlineArray8(8,'class','login_button','md-button','','style','color: white;','type','submit'),this.debug(12,6,6));
    this.compView_12 = new import32.View_MdButton0(this.viewUtils,this,12,this._el_12);
    this._MdButton_12_3 = new import32.Wrapper_MdButton(new import35.ElementRef(this._el_12),this.renderer);
    this._text_13 = this.renderer.createText((null as any),'Login',this.debug(13,6,99));
    this.compView_12.create(this._MdButton_12_3.context);
    this._text_14 = this.renderer.createText(this._el_6,'\n    ',this.debug(14,6,113));
    this._text_15 = this.renderer.createText(this._el_2,'\n    ',this.debug(15,7,11));
    this._el_16 = import5.createRenderElement(this.renderer,this._el_2,'p',new import5.InlineArray2(2,'class','text login_footer'),this.debug(16,8,4));
    this._text_17 = this.renderer.createText(this._el_16,'\n      Want to help out? Get an invite from a friend or email us.',this.debug(17,8,33));
    this._el_18 = import5.createRenderElement(this.renderer,this._el_16,'br',import5.EMPTY_INLINE_ARRAY,this.debug(18,9,64));
    this._text_19 = this.renderer.createText(this._el_16,'\n      Organization in need of help? ',this.debug(19,9,70));
    this._el_20 = import5.createRenderElement(this.renderer,this._el_16,'a',new import5.InlineArray4(4,'routerLink','/signup','routerLinkActive','active'),this.debug(20,10,36));
    this._RouterLinkWithHref_20_3 = new import33.Wrapper_RouterLinkWithHref(this.parentView.injectorGet(import11.Router,this.parentIndex),this.parentView.injectorGet(import36.ActivatedRoute,this.parentIndex),this.parentView.injectorGet(import37.LocationStrategy,this.parentIndex));
    this._RouterLinkActive_20_4 = new import34.Wrapper_RouterLinkActive(this.parentView.injectorGet(import11.Router,this.parentIndex),new import35.ElementRef(this._el_20),this.renderer);
    this._query_RouterLink_20_0 = new import31.QueryList<any>();
    this._query_RouterLinkWithHref_20_1 = new import31.QueryList<any>();
    this._text_21 = this.renderer.createText(this._el_20,'Sign up here',this.debug(21,10,86));
    this._text_22 = this.renderer.createText(this._el_16,'\n    ',this.debug(22,10,102));
    this._text_23 = this.renderer.createText(this._el_2,'\n  ',this.debug(23,11,8));
    this._text_24 = this.renderer.createText((null as any),'\n',this.debug(24,12,20));
    this.compView_0.create(this._MdCard_0_3.context);
    this._text_25 = this.renderer.createText(parentRenderNode,'\n',this.debug(25,13,10));
    var disposable_0:Function = import5.subscribeToRenderElement(this,this._el_6,new import5.InlineArray8(6,'ngSubmit',(null as any),'submit',(null as any),'reset',(null as any)),this.eventHandler(this.handleEvent_6));
    this._NgForm_6_3.subscribe(this,this.eventHandler(this.handleEvent_6),true);
    var disposable_1:Function = import5.subscribeToRenderElement(this,this._el_8,new import5.InlineArray4(4,'ngModelChange',(null as any),'click',(null as any)),this.eventHandler(this.handleEvent_8));
    this._NgModel_8_5.subscribe(this,this.eventHandler(this.handleEvent_8),true);
    var disposable_2:Function = import5.subscribeToRenderElement(this,this._el_10,new import5.InlineArray4(4,'ngModelChange',(null as any),'click',(null as any)),this.eventHandler(this.handleEvent_10));
    this._NgModel_10_5.subscribe(this,this.eventHandler(this.handleEvent_10),true);
    var disposable_3:Function = import5.subscribeToRenderElement(this,this._el_12,new import5.InlineArray8(8,'click',(null as any),'mousedown',(null as any),'focus',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_12));
    var disposable_4:Function = import5.subscribeToRenderElement(this,this._el_20,new import5.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_20));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._text_23,
      this._text_24,
      this._text_25
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import18.MdInput) && (8 === requestNodeIndex))) { return this._MdInput_8_3.context; }
    if (((token === import19.NG_VALUE_ACCESSOR) && (8 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_8_4; }
    if (((token === import20.NgModel) && (8 === requestNodeIndex))) { return this._NgModel_8_5.context; }
    if (((token === import21.NgControl) && (8 === requestNodeIndex))) { return this._NgControl_8_6; }
    if (((token === import17.NgControlStatus) && (8 === requestNodeIndex))) { return this._NgControlStatus_8_7.context; }
    if (((token === import14.StyleCompatibility) && (8 === requestNodeIndex))) { return this._StyleCompatibility_8_8.context; }
    if (((token === import18.MdInput) && (10 === requestNodeIndex))) { return this._MdInput_10_3.context; }
    if (((token === import19.NG_VALUE_ACCESSOR) && (10 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_10_4; }
    if (((token === import20.NgModel) && (10 === requestNodeIndex))) { return this._NgModel_10_5.context; }
    if (((token === import21.NgControl) && (10 === requestNodeIndex))) { return this._NgControl_10_6; }
    if (((token === import17.NgControlStatus) && (10 === requestNodeIndex))) { return this._NgControlStatus_10_7.context; }
    if (((token === import14.StyleCompatibility) && (10 === requestNodeIndex))) { return this._StyleCompatibility_10_8.context; }
    if (((token === import22.MdButton) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._MdButton_12_3.context; }
    if (((token === import15.NgForm) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._NgForm_6_3.context; }
    if (((token === import16.ControlContainer) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._ControlContainer_6_4; }
    if (((token === import17.NgControlStatusGroup) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._NgControlStatusGroup_6_5.context; }
    if (((token === import23.RouterLinkWithHref) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._RouterLinkWithHref_20_3.context; }
    if (((token === import24.RouterLinkActive) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._RouterLinkActive_20_4.context; }
    if (((token === import13.MdCardContent) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._MdCardContent_2_3.context; }
    if (((token === import14.StyleCompatibility) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._StyleCompatibility_2_4.context; }
    if (((token === import13.MdCard) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 24)))) { return this._MdCard_0_3.context; }
    if (((token === import14.StyleCompatibility) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 24)))) { return this._StyleCompatibility_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.debug(0,0,0);
    if (this._MdCard_0_3.ngDoCheck(this,this._el_0,throwOnChange)) { this.compView_0.markAsCheckOnce(); }
    this._StyleCompatibility_0_4.ngDoCheck(this,this._el_0,throwOnChange);
    this.debug(2,1,2);
    this._MdCardContent_2_3.ngDoCheck(this,this._el_2,throwOnChange);
    this._StyleCompatibility_2_4.ngDoCheck(this,this._el_2,throwOnChange);
    this.debug(6,3,4);
    this._NgForm_6_3.ngDoCheck(this,this._el_6,throwOnChange);
    this._NgControlStatusGroup_6_5.ngDoCheck(this,this._el_6,throwOnChange);
    this.debug(8,4,37);
    const currVal_8_0_0:any = 'start';
    this._MdInput_8_3.check_align(currVal_8_0_0,throwOnChange,false);
    this.debug(8,4,51);
    const currVal_8_0_1:any = 'email_input';
    this._MdInput_8_3.check_id(currVal_8_0_1,throwOnChange,false);
    this.debug(8,4,16);
    const currVal_8_0_2:any = 'E-Mail';
    this._MdInput_8_3.check_placeholder(currVal_8_0_2,throwOnChange,false);
    this.debug(8,4,68);
    const currVal_8_0_3:any = 'username';
    this._MdInput_8_3.check_name(currVal_8_0_3,throwOnChange,false);
    this._MdInput_8_3.ngDoCheck(this,this._el_8,throwOnChange);
    this.debug(8,4,68);
    const currVal_8_1_0:any = 'username';
    this._NgModel_8_5.check_name(currVal_8_1_0,throwOnChange,false);
    this.debug(8,4,124);
    const currVal_8_1_1:any = this.context.credentials.userid;
    this._NgModel_8_5.check_model(currVal_8_1_1,throwOnChange,false);
    this._NgModel_8_5.ngDoCheck(this,this._el_8,throwOnChange);
    this.debug(8,4,6);
    this._NgControlStatus_8_7.ngDoCheck(this,this._el_8,throwOnChange);
    this._StyleCompatibility_8_8.ngDoCheck(this,this._el_8,throwOnChange);
    this.debug(10,5,39);
    const currVal_10_0_0:any = 'start';
    this._MdInput_10_3.check_align(currVal_10_0_0,throwOnChange,false);
    this.debug(10,5,53);
    const currVal_10_0_1:any = 'password_input';
    this._MdInput_10_3.check_id(currVal_10_0_1,throwOnChange,false);
    this.debug(10,5,16);
    const currVal_10_0_2:any = 'Password';
    this._MdInput_10_3.check_placeholder(currVal_10_0_2,throwOnChange,false);
    this.debug(10,5,89);
    const currVal_10_0_3:any = 'password';
    this._MdInput_10_3.check_type(currVal_10_0_3,throwOnChange,false);
    this.debug(10,5,73);
    const currVal_10_0_4:any = 'password';
    this._MdInput_10_3.check_name(currVal_10_0_4,throwOnChange,false);
    this._MdInput_10_3.ngDoCheck(this,this._el_10,throwOnChange);
    this.debug(10,5,73);
    const currVal_10_1_0:any = 'password';
    this._NgModel_10_5.check_name(currVal_10_1_0,throwOnChange,false);
    this.debug(10,5,145);
    const currVal_10_1_1:any = this.context.credentials.password;
    this._NgModel_10_5.check_model(currVal_10_1_1,throwOnChange,false);
    this._NgModel_10_5.ngDoCheck(this,this._el_10,throwOnChange);
    this.debug(10,5,6);
    this._NgControlStatus_10_7.ngDoCheck(this,this._el_10,throwOnChange);
    this._StyleCompatibility_10_8.ngDoCheck(this,this._el_10,throwOnChange);
    this.debug(12,6,6);
    if (this._MdButton_12_3.ngDoCheck(this,this._el_12,throwOnChange)) { this.compView_12.markAsCheckOnce(); }
    this.debug(20,10,39);
    const currVal_20_0_0:any = '/signup';
    this._RouterLinkWithHref_20_3.check_routerLink(currVal_20_0_0,throwOnChange,false);
    this._RouterLinkWithHref_20_3.ngDoCheck(this,this._el_20,throwOnChange);
    this.debug(20,10,60);
    const currVal_20_1_0:any = 'active';
    this._RouterLinkActive_20_4.check_routerLinkActive(currVal_20_1_0,throwOnChange,false);
    this._RouterLinkActive_20_4.ngDoCheck(this,this._el_20,throwOnChange);
    if (!throwOnChange) {
      if (this._query_MdHint_8_1.dirty) {
        this._query_MdHint_8_1.reset(([] as any[]));
        this._MdInput_8_3.context._hintChildren = this._query_MdHint_8_1;
        this._query_MdHint_8_1.notifyOnChanges();
      }
      if (this._query_MdHint_10_1.dirty) {
        this._query_MdHint_10_1.reset(([] as any[]));
        this._MdInput_10_3.context._hintChildren = this._query_MdHint_10_1;
        this._query_MdHint_10_1.notifyOnChanges();
      }
      if (this._query_RouterLink_20_0.dirty) {
        this._query_RouterLink_20_0.reset(([] as any[]));
        this._RouterLinkActive_20_4.context.links = this._query_RouterLink_20_0;
        this._query_RouterLink_20_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_20_1.dirty) {
        this._query_RouterLinkWithHref_20_1.reset([this._RouterLinkWithHref_20_3.context]);
        this._RouterLinkActive_20_4.context.linksWithHrefs = this._query_RouterLinkWithHref_20_1;
        this._query_RouterLinkWithHref_20_1.notifyOnChanges();
      }
      this.debug(8,4,6);
      if ((this.numberOfChecks === 0)) { this._MdInput_8_3.context.ngAfterContentInit(); }
      this.debug(10,5,6);
      if ((this.numberOfChecks === 0)) { this._MdInput_10_3.context.ngAfterContentInit(); }
      this.debug(20,10,36);
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_20_4.context.ngAfterContentInit(); }
    }
    this._NgControlStatusGroup_6_5.checkHost(this,this,this._el_6,throwOnChange);
    this._MdInput_8_3.checkHost(this,this.compView_8,this._el_8,throwOnChange);
    this._NgControlStatus_8_7.checkHost(this,this.compView_8,this._el_8,throwOnChange);
    this._MdInput_10_3.checkHost(this,this.compView_10,this._el_10,throwOnChange);
    this._NgControlStatus_10_7.checkHost(this,this.compView_10,this._el_10,throwOnChange);
    this._MdButton_12_3.checkHost(this,this.compView_12,this._el_12,throwOnChange);
    this._RouterLinkWithHref_20_3.checkHost(this,this,this._el_20,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
    this.compView_8.detectChanges(throwOnChange);
    this.compView_10.detectChanges(throwOnChange);
    this.compView_12.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this.compView_8.destroy();
    this.compView_10.destroy();
    this.compView_12.destroy();
    this._MdInput_8_3.ngOnDestroy();
    this._NgModel_8_5.ngOnDestroy();
    this.debug(8,4,6);
    this._MdInput_10_3.ngOnDestroy();
    this._NgModel_10_5.ngOnDestroy();
    this.debug(10,5,6);
    this.debug(12,6,6);
    this._NgForm_6_3.ngOnDestroy();
    this.debug(6,3,4);
    this._RouterLinkWithHref_20_3.ngOnDestroy();
    this._RouterLinkActive_20_4.ngOnDestroy();
    this.debug(20,10,36);
    this.debug(2,1,2);
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 0) && (ngContentIndex == 0))) {
      cb(this._text_1,ctx);
      cb(this._el_2,ctx);
      cb(this._text_24,ctx);
    }
    if (((nodeIndex == 8) && (ngContentIndex == 0))) {  }
    if (((nodeIndex == 8) && (ngContentIndex == 1))) {  }
    if (((nodeIndex == 8) && (ngContentIndex == 2))) {  }
    if (((nodeIndex == 8) && (ngContentIndex == 3))) {  }
    if (((nodeIndex == 10) && (ngContentIndex == 0))) {  }
    if (((nodeIndex == 10) && (ngContentIndex == 1))) {  }
    if (((nodeIndex == 10) && (ngContentIndex == 2))) {  }
    if (((nodeIndex == 10) && (ngContentIndex == 3))) {  }
    if (((nodeIndex == 12) && (ngContentIndex == 0))) { cb(this._text_13,ctx); }
  }
  handleEvent_6(eventName:string,$event:any):boolean {
    this.debug(6,3,4);
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._NgForm_6_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngSubmit')) {
      const pd_sub_0:any = ((<any>this.context.login()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_8(eventName:string,$event:any):boolean {
    this.debug(8,4,6);
    this.compView_8.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdInput_8_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.credentials.userid = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_10(eventName:string,$event:any):boolean {
    this.debug(10,5,6);
    this.compView_10.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdInput_10_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'ngModelChange')) {
      const pd_sub_0:any = ((<any>(this.context.credentials.password = $event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_12(eventName:string,$event:any):boolean {
    this.debug(12,6,6);
    this.compView_12.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdButton_12_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.login()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_20(eventName:string,$event:any):boolean {
    this.debug(20,10,36);
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLinkWithHref_20_3.handleEvent(eventName,$event) && result);
    return result;
  }
}